/**
 * PDF Export Service — uses pdfkit exclusively (pure-JS, Alpine-safe).
 * Charts are drawn with pdfkit vector primitives (no canvas/browser deps).
 */
import PDFDocument from 'pdfkit';
import { connectToMongo } from '../../config/mongo';
import { JobRepository } from '../job/job.repository';
import { AuditReportsService } from '../audit_reports/audit_reports.service';

// ─── Brand colours ────────────────────────────────────────────────────────────

const C = {
  black: '#09090B',
  white: '#FFFFFF',
  gold: '#D4A853',
  goldLight: '#F5D78C',
  zinc900: '#18181B',
  zinc800: '#27272A',
  zinc700: '#3F3F46',
  zinc500: '#71717A',
  zinc400: '#A1A1AA',
  zinc300: '#D4D4D8',
  emerald: '#10B981',
  red: '#EF4444',
  amber: '#F59E0B',
  blue: '#3B82F6',
  purple: '#8B5CF6',
};

// ─── Layout constants ────────────────────────────────────────────────────────

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const ML = 48;
const MR = 48;
const CONTENT_W = PAGE_W - ML - MR;

// ─── Buffer helper ────────────────────────────────────────────────────────────

function pdfToBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

// ─── Shared header / footer ───────────────────────────────────────────────────

function drawPageHeader(doc: PDFKit.PDFDocument, title: string, subtitle: string, domain: string) {
  // Gold left accent bar
  doc.rect(0, 0, 4, PAGE_H).fill(C.gold);

  // Header background
  doc.rect(0, 0, PAGE_W, 80).fill(C.zinc900);

  // Logo / brand
  doc
    .fillColor(C.white)
    .font('Helvetica-Bold')
    .fontSize(15)
    .text('COLYTICS AI', ML, 22, { width: CONTENT_W / 2 });

  doc.fillColor(C.gold).font('Helvetica').fontSize(9).text('Intelligence Platform', ML, 40);

  // Report title (right side)
  doc
    .fillColor(C.white)
    .font('Helvetica-Bold')
    .fontSize(13)
    .text(title, PAGE_W / 2, 20, { width: PAGE_W / 2 - MR, align: 'right' });

  doc
    .fillColor(C.zinc400)
    .font('Helvetica')
    .fontSize(9)
    .text(subtitle, PAGE_W / 2, 38, { width: PAGE_W / 2 - MR, align: 'right' });

  doc
    .fillColor(C.zinc500)
    .font('Helvetica')
    .fontSize(8)
    .text(`Domain: ${domain}`, PAGE_W / 2, 54, { width: PAGE_W / 2 - MR, align: 'right' });

  // Thin gold divider below header
  doc.rect(ML, 86, CONTENT_W, 1).fill(C.gold);
}

function drawFooter(doc: PDFKit.PDFDocument, pageNum: number) {
  const y = PAGE_H - 30;
  doc.rect(0, PAGE_H - 36, PAGE_W, 36).fill(C.zinc900);
  doc
    .fillColor(C.zinc500)
    .font('Helvetica')
    .fontSize(7.5)
    .text(
      `Generated by Colytics AI  •  ${new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}`,
      ML,
      y,
      { width: CONTENT_W - 40 },
    );
  doc.fillColor(C.zinc400).fontSize(7.5).text(`Page ${pageNum}`, PAGE_W - MR - 30, y, { width: 30, align: 'right' });
}

// ─── Section label ────────────────────────────────────────────────────────────

function sectionLabel(doc: PDFKit.PDFDocument, label: string, y: number) {
  doc.rect(ML, y, 3, 12).fill(C.gold);
  doc.fillColor(C.white).font('Helvetica-Bold').fontSize(10).text(label, ML + 10, y + 1);
  return y + 22;
}

// ─── KPI cards row ────────────────────────────────────────────────────────────

function drawKpiRow(
  doc: PDFKit.PDFDocument,
  y: number,
  items: Array<{ label: string; value: string | number; sub?: string; color?: string }>,
) {
  const colW = CONTENT_W / items.length;
  items.forEach((item, i) => {
    const x = ML + i * colW;
    const color = item.color ?? C.gold;
    // Card fill
    doc.roundedRect(x + 2, y, colW - 6, 54, 5).fill(C.zinc900);
    // Top accent
    doc.rect(x + 2, y, colW - 6, 2).fill(color);
    // Value
    doc.fillColor(color).font('Helvetica-Bold').fontSize(22).text(String(item.value), x + 10, y + 8, { width: colW - 20, align: 'center' });
    // Label
    doc.fillColor(C.zinc300).font('Helvetica').fontSize(8).text(item.label, x + 10, y + 32, { width: colW - 20, align: 'center' });
    if (item.sub) {
      doc.fillColor(C.zinc500).fontSize(7).text(item.sub, x + 10, y + 43, { width: colW - 20, align: 'center' });
    }
  });
  return y + 63;
}

// ─── Horizontal bar chart ─────────────────────────────────────────────────────

function drawHBarChart(
  doc: PDFKit.PDFDocument,
  y: number,
  bars: Array<{ label: string; value: number; max: number; color?: string }>,
  height = 18,
  gap = 6,
) {
  const chartW = CONTENT_W - 100;
  const labelW = 96;
  let cy = y;
  bars.forEach((bar) => {
    const pct = Math.min(1, bar.value / bar.max);
    const fillW = pct * chartW;
    const color = bar.color ?? C.gold;

    // Label
    doc.fillColor(C.zinc400).font('Helvetica').fontSize(8).text(bar.label, ML, cy + 4, { width: labelW });

    // Background track
    doc.rect(ML + labelW, cy, chartW, height).fill(C.zinc800);
    // Fill
    if (fillW > 0) {
      doc.rect(ML + labelW, cy, fillW, height).fill(color);
    }
    // Value text
    doc
      .fillColor(C.white)
      .font('Helvetica-Bold')
      .fontSize(8)
      .text(`${Math.round(bar.value)}`, ML + labelW + fillW + 4, cy + 4);

    cy += height + gap;
  });
  return cy + 4;
}

// ─── Vertical bar chart  ─────────────────────────────────────────────────────

function drawVBarChart(
  doc: PDFKit.PDFDocument,
  y: number,
  bars: Array<{ label: string; value: number }>,
  maxVal: number,
  chartH = 80,
  colors?: string[],
) {
  const BAR_W = Math.min(30, (CONTENT_W - 20) / bars.length - 6);
  const totalW = bars.length * (BAR_W + 6) - 6;
  const startX = ML + (CONTENT_W - totalW) / 2;

  bars.forEach((bar, i) => {
    const x = startX + i * (BAR_W + 6);
    const fillH = maxVal > 0 ? (bar.value / maxVal) * chartH : 0;
    const color = colors?.[i % (colors?.length ?? 1)] ?? C.gold;
    const barY = y + chartH - fillH;

    // Background
    doc.rect(x, y, BAR_W, chartH).fill(C.zinc800);
    // Fill
    if (fillH > 0) {
      doc.rect(x, barY, BAR_W, fillH).fill(color);
    }
    // Value
    if (bar.value > 0) {
      doc
        .fillColor(C.white)
        .font('Helvetica-Bold')
        .fontSize(7)
        .text(String(Math.round(bar.value)), x, barY - 10, { width: BAR_W, align: 'center' });
    }
    // Label
    doc
      .fillColor(C.zinc400)
      .font('Helvetica')
      .fontSize(7)
      .text(bar.label, x - 4, y + chartH + 4, { width: BAR_W + 8, align: 'center' });
  });
  return y + chartH + 22;
}

// ─── Donut / gauge  ──────────────────────────────────────────────────────────

function drawScoreGauge(doc: PDFKit.PDFDocument, cx: number, cy: number, score: number | null, label: string, color: string) {
  const r = 34;
  const val = score ?? 0;
  // Outer ring (track)
  doc.circle(cx, cy, r).lineWidth(7).strokeColor(C.zinc800).stroke();
  // Score arc (simulate with overlapping fill — pdfkit arc via bezier)
  // We'll use a simple arc technique using strokeColor
  if (val > 0) {
    // pdfkit doesn't have direct arc(), use path
    const startAngle = -Math.PI / 2;
    const sweepAngle = (val / 100) * 2 * Math.PI;
    const endAngle = startAngle + sweepAngle;

    doc
      .path(arcPath(cx, cy, r, startAngle, endAngle))
      .lineWidth(7)
      .strokeColor(color)
      .stroke();
  }
  // Center text
  doc
    .fillColor(color)
    .font('Helvetica-Bold')
    .fontSize(16)
    .text(score !== null ? `${score}` : 'N/A', cx - r, cy - 10, { width: r * 2, align: 'center' });
  doc
    .fillColor(C.zinc400)
    .font('Helvetica')
    .fontSize(7)
    .text(label, cx - r, cy + 10, { width: r * 2, align: 'center' });
}

function arcPath(cx: number, cy: number, r: number, startAngle: number, endAngle: number): string {
  // Create SVG-style arc path
  const x1 = cx + r * Math.cos(startAngle);
  const y1 = cy + r * Math.sin(startAngle);
  const x2 = cx + r * Math.cos(endAngle);
  const y2 = cy + r * Math.sin(endAngle);
  const largeArc = endAngle - startAngle > Math.PI ? 1 : 0;
  return `M ${x1} ${y1} A ${r} ${r} 0 ${largeArc} 1 ${x2} ${y2}`;
}

// ─── Simple table ─────────────────────────────────────────────────────────────

function drawTable(
  doc: PDFKit.PDFDocument,
  y: number,
  headers: string[],
  rows: string[][],
  colWidths?: number[],
  maxRows = 20,
) {
  const widths = colWidths ?? headers.map(() => CONTENT_W / headers.length);
  const ROW_H = 18;

  // Header row
  doc.rect(ML, y, CONTENT_W, ROW_H).fill(C.zinc800);
  let hx = ML;
  headers.forEach((h, i) => {
    doc.fillColor(C.gold).font('Helvetica-Bold').fontSize(8).text(h, hx + 4, y + 5, { width: widths[i] - 8 });
    hx += widths[i];
  });
  y += ROW_H;

  // Data rows
  const displayRows = rows.slice(0, maxRows);
  displayRows.forEach((row, ri) => {
    const bg = ri % 2 === 0 ? C.zinc900 : '#16161A';
    doc.rect(ML, y, CONTENT_W, ROW_H).fill(bg);
    let rx = ML;
    row.forEach((cell, ci) => {
      doc.fillColor(C.zinc300).font('Helvetica').fontSize(7.5).text(cell, rx + 4, y + 5, { width: widths[ci] - 8 });
      rx += widths[ci];
    });
    y += ROW_H;
  });

  if (rows.length > maxRows) {
    doc.fillColor(C.zinc500).font('Helvetica').fontSize(7).text(`…and ${rows.length - maxRows} more`, ML, y + 3);
    y += 14;
  }

  return y + 8;
}

// ─── Severity badge text ─────────────────────────────────────────────────────

function badgeColor(severity: string): string {
  if (severity === 'critical') return C.red;
  if (severity === 'warning') return C.amber;
  return C.blue;
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── WEEKLY SUMMARY PDF ──────────────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildWeeklySummaryPdf(jobId: string, domain: string): Promise<Buffer> {
  const db = await connectToMongo();
  const jobRepo = new JobRepository();
  const effectiveId = await jobRepo.resolveEffectiveJobId(jobId);

  // ── Fetch data in parallel ──────────────────────────────────────────────
    const [aivsDoc, pageStats, moduleE, jobSummary, topActionsRaw] = await Promise.all([
    db.collection('module_c').findOne({ jobId: effectiveId }, { projection: { overall_score: 1, model_scores: 1 }, sort: { timestamp: -1 } } as any),
    db.collection('fields').aggregate([
      { $match: { jobId: effectiveId } },
      { $group: { _id: null, avg_health: { $avg: { $ifNull: ['$recommendations.health_score', 100] } }, total: { $sum: 1 } } },
    ]).toArray(),
    db.collection('module_e').findOne({ jobId: effectiveId }, { projection: { brand_analysis: 1, ai_share_of_voice: 1, ai_sov_history: 1, score_history: 1 } }),
    db.collection('job_summaries').findOne({ jobId: effectiveId }, { projection: { total_pages: 1, completed_at: 1 } }),
    db.collection('fields').aggregate([
      { $match: { jobId: effectiveId } },
      { $unwind: { path: '$recommendations.recommendations', preserveNullAndEmptyArrays: false } },
      { $group: { _id: '$recommendations.recommendations.title', title: { $first: '$recommendations.recommendations.title' }, severity: { $first: '$recommendations.recommendations.severity' }, category: { $first: '$recommendations.recommendations.category' }, count: { $sum: 1 } } },
      { $addFields: { order: { $switch: { branches: [{ case: { $eq: ['$severity', 'critical'] }, then: 1 }, { case: { $eq: ['$severity', 'warning'] }, then: 2 }], default: 3 } } } },
      { $sort: { order: 1, count: -1 } },
      { $limit: 8 },
    ]).toArray(),
  ]);

  const aivsScore: number | null = typeof aivsDoc?.overall_score === 'number' ? Math.round(aivsDoc.overall_score) : null;
  const healthScore: number | null = pageStats[0]?.avg_health != null ? Math.round(pageStats[0].avg_health) : null;
  const citations: number | null = (moduleE as any)?.brand_analysis?.total_mentions ?? null;
  const sov: number | null = (moduleE as any)?.ai_share_of_voice?.overall_sov ?? null;
  const pagesCrawled: number | null = (jobSummary as any)?.total_pages ?? null;
  const crawlDate = (jobSummary as any)?.completed_at
    ? new Date((jobSummary as any).completed_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
    : 'N/A';

  // Model-wise AIVS scores for bar chart
  const modelScores: Array<{ label: string; value: number }> = [];
  const ms = (aivsDoc as any)?.model_scores ?? {};
  const modelMap: Record<string, string> = { chatgpt: 'ChatGPT', gemini: 'Gemini', perplexity: 'Perplexity', claude: 'Claude' };
  Object.entries(modelMap).forEach(([k, label]) => {
    if (typeof ms[k] === 'number') modelMap[k] && modelScores.push({ label, value: Math.round(ms[k]) });
  });

  // SOV history for trend
  const sovHistory: Array<{ label: string; value: number }> = ((moduleE as any)?.ai_sov_history ?? [])
    .slice(-6)
    .map((h: any) => ({
      label: h.date ? new Date(h.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : '',
      value: typeof h.overall_sov === 'number' ? Math.round(h.overall_sov) : 0,
    }));

  // ── Build PDF ───────────────────────────────────────────────────────────
  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'Weekly Summary Report', Author: 'Colytics AI' } });

  drawPageHeader(doc, 'Weekly Summary', `Report Date: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`, domain);

  let y = 102;

  // ── KPI Section ──────────────────────────────────────────────────────────
  y = sectionLabel(doc, 'KEY PERFORMANCE INDICATORS', y);
  y = drawKpiRow(doc, y, [
    { label: 'AI Visibility Score', value: aivsScore !== null ? aivsScore : 'N/A', color: C.gold },
    { label: 'Website Health', value: healthScore !== null ? `${healthScore}%` : 'N/A', color: C.emerald },
    { label: 'Total Citations', value: citations !== null ? citations : '—', color: C.blue },
    { label: 'Share of Voice', value: sov !== null ? `${sov.toFixed(1)}%` : '—', color: C.purple },
  ]);

  y += 6;

  // ── AIVS Gauge + Model breakdown ──────────────────────────────────────────
  if (aivsScore !== null) {
    y = sectionLabel(doc, 'AI VISIBILITY — MODEL BREAKDOWN', y);

    if (modelScores.length > 0) {
      const maxScore = 100;
      y = drawHBarChart(doc, y, modelScores.map(m => ({ label: m.label, value: m.value, max: maxScore, color: C.gold })));
    } else {
      // Single gauge
      drawScoreGauge(doc, ML + 60, y + 50, aivsScore, 'AIVS Score', C.gold);
      y += 110;
    }
  }

  y += 6;

  // ── SOV trend ────────────────────────────────────────────────────────────
  if (sovHistory.length >= 2) {
    y = sectionLabel(doc, 'SHARE OF VOICE — TREND (LAST 6 PERIODS)', y);
    y = drawVBarChart(doc, y, sovHistory, 100, 70, [C.gold, C.goldLight, C.amber, C.gold, C.goldLight, C.amber]);
  }

  // ── Crawl stats ───────────────────────────────────────────────────────────
  y = sectionLabel(doc, 'CRAWL SUMMARY', y);
  y = drawKpiRow(doc, y, [
    { label: 'Pages Crawled', value: pagesCrawled !== null ? pagesCrawled : 'N/A', color: C.zinc300 },
    { label: 'Last Crawl', value: crawlDate, color: C.zinc300 },
    { label: 'Domain', value: domain, color: C.zinc300 },
    { label: 'Report Period', value: 'Weekly', color: C.zinc300 },
  ]);

  y += 8;

  // ── Top Actions ───────────────────────────────────────────────────────────
  if (topActionsRaw.length > 0) {
    y = sectionLabel(doc, 'TOP PRIORITY ACTIONS', y);
    const rows = topActionsRaw.map((a: any) => [
      a.title ?? '',
      `${a.category ?? ''}`,
      `${a.severity ?? ''}`.toUpperCase(),
      String(a.count ?? 0),
    ]);
    y = drawTable(doc, y, ['Action', 'Category', 'Severity', 'Pages'], rows, [220, 110, 80, 60]);
  }

  drawFooter(doc, 1);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── AUDIT REPORT PDF ────────────────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildAuditReportPdf(jobId: string, userId: string, domain: string): Promise<Buffer> {
  const auditService = new AuditReportsService();
  const report = await auditService.getReport(userId, jobId);

  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'Audit Report', Author: 'Colytics AI' } });

  const title = 'Technical Audit Report';
  const subtitle = `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`;
  drawPageHeader(doc, title, subtitle, domain);

  let y = 102;

  // ── Summary scorecards ────────────────────────────────────────────────────
  y = sectionLabel(doc, 'AUDIT SUMMARY', y);
  const s = report.report.summary;
  y = drawKpiRow(doc, y, [
    { label: 'Critical Issues', value: s.critical, color: C.red },
    { label: 'Warnings', value: s.warning, color: C.amber },
    { label: 'Total Issues', value: s.total, color: C.zinc400 },
    { label: 'Info', value: s.info, color: C.blue },
  ]);

  y += 8;

  // ── Issues bar chart (by severity) ───────────────────────────────────────
  y = sectionLabel(doc, 'ISSUES BY SEVERITY', y);
  y = drawHBarChart(doc, y, [
    { label: 'Critical', value: s.critical, max: Math.max(s.total, 1), color: C.red },
    { label: 'Warning', value: s.warning, max: Math.max(s.total, 1), color: C.amber },
    { label: 'Info', value: s.info, max: Math.max(s.total, 1), color: C.blue },
  ]);

  y += 8;

  // ── Issues by category ────────────────────────────────────────────────────
  const categories: Record<string, { critical: number; warning: number; info: number }> = {};
  report.report.issues.forEach((issue) => {
    if (!categories[issue.category]) categories[issue.category] = { critical: 0, warning: 0, info: 0 };
    categories[issue.category][issue.severity]++;
  });

  if (Object.keys(categories).length > 0) {
    y = sectionLabel(doc, 'ISSUES BY CATEGORY', y);
    const catRows = Object.entries(categories).map(([cat, counts]) => [
      cat.replace(/_/g, ' ').toUpperCase(),
      String(counts.critical),
      String(counts.warning),
      String(counts.info),
    ]);
    y = drawTable(doc, y, ['Category', 'Critical', 'Warning', 'Info'], catRows, [200, 100, 100, 70]);
  }

  y += 6;

  // ── Detailed issues list ──────────────────────────────────────────────────
  y = sectionLabel(doc, 'ISSUE DETAILS', y);

  const PAGE_BREAK_Y = PAGE_H - 60;
  let pageNum = 1;

  report.report.issues.forEach((issue) => {
    if (y > PAGE_BREAK_Y) {
      drawFooter(doc, pageNum);
      doc.addPage({ size: 'A4', margin: 0 });
      pageNum++;
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }

    // Issue card header
    const color = badgeColor(issue.severity);
    doc.rect(ML, y, CONTENT_W, 2).fill(color);
    y += 4;

    doc.fillColor(color).font('Helvetica-Bold').fontSize(9).text(`[${issue.severity.toUpperCase()}] ${issue.title}`, ML, y);
    y += 13;
    doc.fillColor(C.zinc300).font('Helvetica').fontSize(8).text(issue.description, ML + 4, y, { width: CONTENT_W - 8 });
    y += doc.heightOfString(issue.description, { width: CONTENT_W - 8 }) + 4;

    doc.fillColor(C.zinc500).fontSize(7.5).text(`Affected: ${issue.affected_count} pages`, ML + 4, y);
    y += 11;

    if (issue.fix) {
      doc.fillColor(C.emerald).fontSize(7.5).text(`Fix: ${issue.fix}`, ML + 4, y, { width: CONTENT_W - 8 });
      y += doc.heightOfString(issue.fix, { width: CONTENT_W - 8 }) + 4;
    }

    if (issue.example_urls.length > 0) {
      doc.fillColor(C.zinc500).fontSize(6.5).text(`Examples: ${issue.example_urls.slice(0, 2).join('  •  ')}`, ML + 4, y, { width: CONTENT_W - 8 });
      y += 10;
    }

    y += 6;
  });

  drawFooter(doc, pageNum);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── COMPETITOR REPORT PDF ───────────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildCompetitorReportPdf(jobId: string, domain: string): Promise<Buffer> {
  const db = await connectToMongo();
  const jobRepo = new JobRepository();
  const effectiveId = await jobRepo.resolveEffectiveJobId(jobId);

  const moduleE = await db.collection('module_e').findOne({ jobId: effectiveId });
  const competitors: any[] = (moduleE as any)?.competitor_mentions ?? [];
  const sovData: any = (moduleE as any)?.ai_share_of_voice ?? {};

  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'Competitor Report', Author: 'Colytics AI' } });
  const title = 'Competitor Intelligence Report';
  const subtitle = `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`;
  drawPageHeader(doc, title, subtitle, domain);

  let y = 102;

  // ── SOV Overview ───────────────────────────────────────────────────────
  y = sectionLabel(doc, 'SHARE OF VOICE OVERVIEW', y);
  const overallSov = typeof sovData.overall_sov === 'number' ? sovData.overall_sov.toFixed(1) : 'N/A';
  y = drawKpiRow(doc, y, [
    { label: 'Your Share of Voice', value: `${overallSov}%`, color: C.gold },
    { label: 'Competitive Position', value: sovData.rank ? `#${sovData.rank}` : '—', color: C.zinc300 },
    { label: 'Models Tracked', value: '4', color: C.blue },
    { label: 'Domain', value: domain.replace(/^https?:\/\//, ''), color: C.zinc300 },
  ]);

  y += 8;

  // ── Model SOV chart ───────────────────────────────────────────────────
  if (sovData.model_breakdown) {
    y = sectionLabel(doc, 'SHARE OF VOICE BY MODEL', y);
    const modelBars: Array<{ label: string; value: number }> = Object.entries(sovData.model_breakdown).map(([k, v]) => ({
      label: k.charAt(0).toUpperCase() + k.slice(1),
      value: typeof v === 'number' ? Math.round(v) : 0,
    }));
    if (modelBars.length > 0) {
      y = drawHBarChart(doc, y, modelBars.map(m => ({ label: m.label, value: m.value, max: 100, color: C.gold })));
    }
  }

  y += 6;

  // ── Competitor mentions table ───────────────────────────────────────
  if (competitors.length > 0) {
    y = sectionLabel(doc, 'TOP COMPETITORS BY AI MENTION', y);
    const rows = competitors.slice(0, 15).map((c: any) => [
      c.domain ?? c.brand ?? '',
      String(c.mention_count ?? c.total_mentions ?? 0),
      c.sentiment?.label ?? '—',
      c.models?.join(', ') ?? '—',
    ]);
    y = drawTable(doc, y, ['Competitor', 'Mentions', 'Sentiment', 'Models'], rows, [200, 80, 100, 120]);
  } else {
    doc.fillColor(C.zinc500).font('Helvetica').fontSize(9).text('No competitor data available for this job.', ML, y + 12);
    y += 30;
  }

  drawFooter(doc, 1);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── AI VISIBILITY SCORECARD PDF ─────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildAiScorecardPdf(jobId: string, domain: string): Promise<Buffer> {
  const db = await connectToMongo();
  const jobRepo = new JobRepository();
  const effectiveId = await jobRepo.resolveEffectiveJobId(jobId);

  const aivsDoc = await db.collection('module_c').findOne(
    { jobId: effectiveId },
    { sort: { timestamp: -1 } } as any,
  );
  const masterAnalysis = aivsDoc?.master_analysis ?? {};
  const modelsList: any[] = masterAnalysis?.models ?? (aivsDoc as any)?.models ?? [];
  const overallScore: number | null = typeof aivsDoc?.overall_score === 'number' ? Math.round(aivsDoc.overall_score) : null;

  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'AI Visibility Scorecard', Author: 'Colytics AI' } });
  const title = 'AI Visibility Scorecard';
  const subtitle = `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`;
  drawPageHeader(doc, title, subtitle, domain);

  let y = 102;

  // ── Overall score ──────────────────────────────────────────────────────
  y = sectionLabel(doc, 'OVERALL AI VISIBILITY SCORE', y);

  const scoreColor = overallScore !== null ? (overallScore >= 80 ? C.emerald : overallScore >= 60 ? C.gold : C.red) : C.zinc500;
  drawScoreGauge(doc, PAGE_W / 2, y + 50, overallScore, 'AIVS Score', scoreColor);
  y += 115;

  // ── Model-by-model scorecards ─────────────────────────────────────────
  if (modelsList.length > 0) {
    y = sectionLabel(doc, 'PERFORMANCE BY MODEL', y);
    y = drawHBarChart(doc, y, modelsList.map((m: any) => ({
      label: typeof m.model === 'string' ? m.model.charAt(0).toUpperCase() + m.model.slice(1) : 'Model',
      value: typeof m.model_wise_performance_score === 'number' ? Math.round(m.model_wise_performance_score) : 0,
      max: 100,
      color: C.gold,
    })));

    y += 8;

    // ── Detailed model table ──────────────────────────────────────────────
    y = sectionLabel(doc, 'MODEL METRIC BREAKDOWN', y);
    const rows = modelsList.map((m: any) => [
      typeof m.model === 'string' ? m.model.charAt(0).toUpperCase() + m.model.slice(1) : '—',
      typeof m.model_wise_performance_score === 'number' ? `${Math.round(m.model_wise_performance_score)}` : '—',
      typeof m.completeness_score === 'number' ? `${Math.round(m.completeness_score)}` : '—',
      typeof m.content_consistency?.score === 'number' ? `${Math.round(m.content_consistency.score)}` : '—',
      typeof m.entity_coverage?.score === 'number' ? `${Math.round(m.entity_coverage.score)}` : '—',
    ]);
    y = drawTable(doc, y, ['Model', 'Perf. Score', 'Completeness', 'Consistency', 'Entity Cov.'], rows, [120, 90, 90, 90, 80]);
  } else {
    doc.fillColor(C.zinc500).font('Helvetica').fontSize(9).text('No model data available for this job.', ML, y + 12);
    y += 30;
  }

  // ── Recommendations ───────────────────────────────────────────────────
  const recommendations: any[] = (aivsDoc as any)?.recommendations ?? [];
  if (recommendations.length > 0) {
    y += 8;
    y = sectionLabel(doc, 'RECOMMENDATIONS', y);
    recommendations.slice(0, 6).forEach((r: any, i) => {
      doc.fillColor(C.gold).font('Helvetica-Bold').fontSize(8).text(`${i + 1}. ${r.title ?? ''}`, ML, y);
      y += 12;
      if (r.issue) {
        doc.fillColor(C.zinc400).font('Helvetica').fontSize(7.5).text(r.issue, ML + 8, y, { width: CONTENT_W - 8 });
        y += doc.heightOfString(r.issue, { width: CONTENT_W - 8 }) + 4;
      }
    });
  }

  drawFooter(doc, 1);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── Public API ───────────────────────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

export class ExportPdfService {
  async generate(
    type: string,
    jobId: string,
    userId: string,
    domain: string,
  ): Promise<Buffer> {
    switch (type) {
      case 'weekly-summary':
        return buildWeeklySummaryPdf(jobId, domain);
      case 'audit-report':
        return buildAuditReportPdf(jobId, userId, domain);
      case 'competitor-report':
        return buildCompetitorReportPdf(jobId, domain);
      case 'ai-scorecard':
        return buildAiScorecardPdf(jobId, domain);
      default:
        throw new Error(`Unknown report type: ${type}`);
    }
  }
}
