import { randomUUID, randomBytes } from 'crypto';
import { connectToMongo } from '../../config/mongo';
import { logger } from '../../shared/logger/logger';
import { JobRepository } from '../job/job.repository';
import type { ApiKeyDoc, ScheduledExportDoc, ReadinessResult } from './export.types';

// ─── Per-export-type readiness config ─────────────────────────────────────────

interface ReadinessConfig {
  /** MongoDB collection to query */
  collection: string;
  /** Strategy: count docs in collection vs inspect a field in a single doc */
  mode: 'count' | 'doc-field';
  /** For mode='doc-field': the field path that must exist and be non-empty */
  field?: string;
  moduleName: string;
  hint: string;
}

const READINESS_MAP: Record<string, ReadinessConfig> = {
  // ─── PDF reports ───────────────────────────────────────────────────────────
  'weekly-summary': {
    collection: 'module_c',
    mode: 'doc-field',
    field: 'overall_score',
    moduleName: 'AI Visibility Analysis',
    hint: 'Run an AI Visibility Analysis for this project first, then come back to download.',
  },
  'audit-report': {
    collection: 'fields',
    mode: 'count',
    moduleName: 'Website Crawl',
    hint: 'Run a website crawl for this project first, then come back to download.',
  },
  'competitor-report': {
    collection: 'module_e',
    mode: 'doc-field',
    field: 'competitor_mentions',
    moduleName: 'Brand & Competitor Intelligence',
    hint: 'Run Brand Intelligence for this project first, then come back to download.',
  },
  'ai-scorecard': {
    collection: 'module_c',
    mode: 'doc-field',
    field: 'overall_score',
    moduleName: 'AI Visibility Analysis',
    hint: 'Run an AI Visibility Analysis for this project first, then come back to download.',
  },
  'serp-analysis': {
    collection: 'serp_results',
    mode: 'count',
    moduleName: 'SERP Analyzer',
    hint: 'Run a SERP Analysis for this project first, then come back to download.',
  },
  'competitor-ai-report': {
    collection: 'module_f',
    mode: 'doc-field',
    field: 'compare_visibility_against_competitors',
    moduleName: 'Competitor AI Intelligence',
    hint: 'Run a Competitor AI Intelligence analysis for this project first, then come back to download.',
  },
  // ─── CSV exports ──────────────────────────────────────────────────────────
  'crawl-data': {
    collection: 'pages',
    mode: 'count',
    moduleName: 'Website Crawl',
    hint: 'Run a website crawl for this project first, then come back to download.',
  },
  'citations': {
    collection: 'module_e',
    mode: 'doc-field',
    field: 'brand_analysis',
    moduleName: 'Brand Intelligence',
    hint: 'Run Brand Intelligence for this project first, then come back to download.',
  },
  'prompts': {
    collection: 'prompt_tracking',
    mode: 'count',
    moduleName: 'Prompt Tracking',
    hint: 'Run a crawl with prompt tracking enabled for this project first, then come back to download.',
  },
  'competitors': {
    collection: 'module_e',
    mode: 'doc-field',
    field: 'competitor_mentions',
    moduleName: 'Competitor Intelligence',
    hint: 'Run Brand Intelligence for this project first, then come back to download.',
  },
  'alerts': {
    collection: 'cbm_alerts',
    mode: 'count',
    moduleName: 'Brand Monitoring',
    hint: 'Alerts are generated by Brand Monitoring. Run Brand Intelligence first, then wait for alert triggers.',
  },
};

// ─── helpers ─────────────────────────────────────────────────────────────────

function generateApiKey(): string {
  // Format: ck_live_<32 random hex chars>
  return `ck_live_${randomBytes(16).toString('hex')}`;
}

// ─── API Key Service ──────────────────────────────────────────────────────────

export class ExportService {
  // ── API key ───────────────────────────────────────────────────────────────

  async getApiKey(userId: string): Promise<ApiKeyDoc | null> {
    const db = await connectToMongo();
    const user = await db.collection('users').findOne({ id: userId }, { projection: { apiKey: 1 } });
    if (!user?.apiKey) return null;
    return user.apiKey as ApiKeyDoc;
  }

  async regenerateApiKey(userId: string): Promise<ApiKeyDoc> {
    const db = await connectToMongo();
    const key = generateApiKey();
    const doc: ApiKeyDoc = {
      key,
      createdAt: new Date().toISOString(),
      lastUsedAt: null,
      rateLimit: 1000,
    };
    await db.collection('users').updateOne({ id: userId }, { $set: { apiKey: doc } });
    logger.info(`[EXPORT] API key regenerated for user ${userId}`);
    return doc;
  }

  async ensureApiKey(userId: string): Promise<ApiKeyDoc> {
    const existing = await this.getApiKey(userId);
    if (existing) return existing;
    return this.regenerateApiKey(userId);
  }

  // ── Scheduled exports ────────────────────────────────────────────────────

  async getSchedule(userId: string): Promise<ScheduledExportDoc | null> {
    const db = await connectToMongo();
    const doc = await db.collection('export_schedules').findOne({ userId });
    if (!doc) return null;
    return {
      id: doc.id,
      userId: doc.userId,
      email: doc.email,
      frequency: doc.frequency,
      reportType: doc.reportType,
      dayOfWeek: doc.dayOfWeek,
      hour: doc.hour,
      createdAt: doc.createdAt,
      updatedAt: doc.updatedAt,
    };
  }

  async saveSchedule(
    userId: string,
    payload: {
      email: string;
      frequency: 'weekly';
      reportType: string;
      dayOfWeek: number;
      hour: number;
    },
  ): Promise<ScheduledExportDoc> {
    const db = await connectToMongo();
    const now = new Date().toISOString();
    const existing = await db.collection('export_schedules').findOne({ userId });
    const id = existing?.id ?? randomUUID();
    const doc: ScheduledExportDoc = {
      id,
      userId,
      email: payload.email,
      frequency: payload.frequency,
      reportType: payload.reportType,
      dayOfWeek: payload.dayOfWeek,
      hour: payload.hour,
      createdAt: existing?.createdAt ?? now,
      updatedAt: now,
    };
    await db.collection('export_schedules').updateOne(
      { userId },
      { $set: doc },
      { upsert: true },
    );
    logger.info(`[EXPORT] Schedule saved for user ${userId}`);
    return doc;
  }

  // ── Most recent completed job for a user ─────────────────────────────────

  async resolveJobId(userId: string, jobId?: string, projectId?: string): Promise<string | null> {
    const db = await connectToMongo();

    if (jobId) {
      // Verify ownership via project lookup
      const job = await db.collection('jobs').findOne({ id: jobId });
      if (!job) return null;
      const project = await db.collection('projects').findOne({
        id: job.projectId,
        userId,
        status: { $ne: 'ARCHIVED' },
      });
      return project ? (job as any).id : null;
    }

    if (projectId) {
      // Verify ownership
      const project = await db.collection('projects').findOne({ id: projectId, userId, status: { $ne: 'ARCHIVED' } });
      if (!project) return null;
      const job = await db.collection('jobs').findOne(
        { projectId, status: 'COMPLETED' },
        { sort: { createdAt: -1 } },
      );
      return job ? (job as any).id : null;
    }

    // Find most recent completed job owned by this user
    const projects = await db
      .collection('projects')
      .find({ userId, status: { $ne: 'ARCHIVED' } }, { projection: { id: 1 } })
      .toArray();

    const projectIds = projects.map((p: any) => p.id);
    if (projectIds.length === 0) return null;

    const job = await db
      .collection('jobs')
      .findOne(
        { projectId: { $in: projectIds }, status: 'COMPLETED' },
        { sort: { createdAt: -1 } },
      );

    return job ? (job as any).id : null;
  }

  // ── Export readiness check ────────────────────────────────────────────────

  /**
   * Collect every COMPLETED job ID for the resolved project, including
   * cache-forwarded effective IDs.  Module C / Module E etc. each create their
   * OWN job (with a different jobType and ID) for the same project, so we need
   * to search across all of them rather than just the single "primary" job.
   */
  private async resolveAllProjectJobIds(
    userId: string,
    jobId?: string,
    projectId?: string,
  ): Promise<{ primaryJobId: string | null; allJobIds: string[] }> {
    const db = await connectToMongo();
    let resolvedProjectId: string | null = null;

    if (jobId) {
      const job = await db.collection('jobs').findOne({ id: jobId });
      if (!job) return { primaryJobId: null, allJobIds: [] };
      const project = await db.collection('projects').findOne({
        id: (job as any).projectId,
        userId,
        status: { $ne: 'ARCHIVED' },
      });
      if (!project) return { primaryJobId: null, allJobIds: [] };
      resolvedProjectId = (job as any).projectId;
    } else if (projectId) {
      const project = await db.collection('projects').findOne({
        id: projectId,
        userId,
        status: { $ne: 'ARCHIVED' },
      });
      if (!project) return { primaryJobId: null, allJobIds: [] };
      resolvedProjectId = projectId;
    } else {
      const projects = await db
        .collection('projects')
        .find({ userId, status: { $ne: 'ARCHIVED' } }, { projection: { id: 1 } })
        .toArray();
      if (projects.length === 0) return { primaryJobId: null, allJobIds: [] };
      const latestJob = await db.collection('jobs').findOne(
        { projectId: { $in: projects.map((p: any) => p.id) }, status: 'COMPLETED' },
        { sort: { createdAt: -1 } },
      );
      if (!latestJob) return { primaryJobId: null, allJobIds: [] };
      resolvedProjectId = (latestJob as any).projectId;
    }

    // All completed jobs for this project (any type)
    const allJobs = await db
      .collection('jobs')
      .find({ projectId: resolvedProjectId, status: 'COMPLETED' }, { projection: { id: 1 } })
      .toArray();

    if (allJobs.length === 0) return { primaryJobId: null, allJobIds: [] };

    const rawIds: string[] = allJobs.map((j: any) => j.id);

    // Resolve cache-forwarding for each job (cacheSourceJobId)
    const jobRepo = new JobRepository();
    const effectiveIds = await Promise.all(rawIds.map((id) => jobRepo.resolveEffectiveJobId(id)));

    const allJobIds = [...new Set([...rawIds, ...effectiveIds])];

    // Primary = most recently created completed job (same as resolveJobId)
    const primaryRaw = await db.collection('jobs').findOne(
      { projectId: resolvedProjectId, status: 'COMPLETED' },
      { sort: { createdAt: -1 } },
    );
    const primaryJobId = primaryRaw ? (primaryRaw as any).id : rawIds[0];

    return { primaryJobId, allJobIds };
  }

  async checkReadiness(
    userId: string,
    type: string,
    jobId?: string,
    projectId?: string,
  ): Promise<ReadinessResult> {
    const config = READINESS_MAP[type];
    if (!config) {
      return {
        ready: false,
        jobId: null,
        effectiveJobId: null,
        dataCount: 0,
        message: `Unknown export type: ${type}`,
        hint: 'Use a valid export type.',
        moduleName: 'Unknown',
      };
    }

    // Step 1 — gather all project job IDs
    const { primaryJobId, allJobIds } = await this.resolveAllProjectJobIds(userId, jobId, projectId);

    if (!primaryJobId || allJobIds.length === 0) {
      return {
        ready: false,
        jobId: null,
        effectiveJobId: null,
        dataCount: 0,
        message: 'No completed analysis found for this project.',
        hint: 'Run a crawl first. Once the job completes, your exports will be available here.',
        moduleName: config.moduleName,
      };
    }

    // Step 2 — check that data exists across ANY of the project's jobs
    const db = await connectToMongo();
    let dataCount = 0;

    try {
      if (config.mode === 'count') {
        dataCount = await db.collection(config.collection).countDocuments({
          jobId: { $in: allJobIds },
        });
      } else {
        // mode = 'doc-field': data lives inside a single document per job
        const doc = await db.collection(config.collection).findOne(
          { jobId: { $in: allJobIds } },
          { projection: { [config.field!]: 1 }, sort: { timestamp: -1 } } as any,
        );
        if (doc) {
          const fieldValue = (doc as any)[config.field!];
          if (Array.isArray(fieldValue)) {
            dataCount = fieldValue.length;
          } else if (fieldValue !== null && fieldValue !== undefined) {
            dataCount = 1;
          }
        }
      }
    } catch (err: any) {
      logger.error(`[EXPORT] readiness check failed for type=${type}: ${err.message}`);
    }

    if (dataCount === 0) {
      return {
        ready: false,
        jobId: primaryJobId,
        effectiveJobId: primaryJobId,
        dataCount: 0,
        message: `No ${config.moduleName} data found for this project.`,
        hint: config.hint,
        moduleName: config.moduleName,
      };
    }

    return {
      ready: true,
      jobId: primaryJobId,
      effectiveJobId: primaryJobId,
      dataCount,
      message: 'Data is ready.',
      hint: '',
      moduleName: config.moduleName,
    };
  }
}
