/**
 * PDF Export Service — uses pdfkit exclusively (pure-JS, Alpine-safe).
 * Charts are drawn with pdfkit vector primitives (no canvas/browser deps).
 */
import PDFDocument from 'pdfkit';
import { connectToMongo } from '../../config/mongo';
import { JobRepository } from '../job/job.repository';
import { AuditReportsService } from '../audit_reports/audit_reports.service';

// ─── Job-ID resolution helper ─────────────────────────────────────────────────
// Module C and Module E each create THEIR OWN jobs (AEO_ANALYSIS, MODULE_E_*…)
// under the same project.  We need ALL completed job IDs for the project so we
// can query module_c / module_e correctly with { jobId: { $in: allJobIds } }.

async function resolveAllProjectJobIds(
  db: Awaited<ReturnType<typeof connectToMongo>>,
  jobId: string,
): Promise<string[]> {
  try {
    const job = await db.collection('jobs').findOne({ id: jobId }, { projection: { projectId: 1 } });
    const projectId = (job as any)?.projectId;
    if (!projectId) return [jobId];

    const allJobs = await db
      .collection('jobs')
      .find(
        { projectId, status: 'COMPLETED' },
        { projection: { id: 1, cacheSourceJobId: 1 } },
      )
      .toArray();

    const ids = new Set<string>();
    for (const j of allJobs) {
      if ((j as any).id) ids.add(String((j as any).id));
      if ((j as any).cacheSourceJobId) ids.add(String((j as any).cacheSourceJobId));
    }
    ids.add(jobId); // always include the seed
    return [...ids];
  } catch {
    return [jobId];
  }
}

// ─── Brand colours ────────────────────────────────────────────────────────────

const C = {
  black: '#09090B',
  white: '#FFFFFF',
  gold: '#D4A853',
  goldLight: '#F5D78C',
  zinc900: '#18181B',
  zinc800: '#27272A',
  zinc700: '#3F3F46',
  zinc500: '#71717A',
  zinc400: '#A1A1AA',
  zinc300: '#D4D4D8',
  emerald: '#10B981',
  red: '#EF4444',
  amber: '#F59E0B',
  blue: '#3B82F6',
  purple: '#8B5CF6',
};

// ─── Layout constants ────────────────────────────────────────────────────────

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const ML = 48;
const MR = 48;
const CONTENT_W = PAGE_W - ML - MR;

// ─── Buffer helper ────────────────────────────────────────────────────────────

function pdfToBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

// ─── Shared header / footer ───────────────────────────────────────────────────

function drawPageHeader(doc: PDFKit.PDFDocument, title: string, subtitle: string, domain: string) {
  // ── Fill ENTIRE page dark — makes all white/zinc text visible everywhere ──
  doc.rect(0, 0, PAGE_W, PAGE_H).fill(C.zinc900);

  // Gold left accent bar
  doc.rect(0, 0, 4, PAGE_H).fill(C.gold);

  // Header background (slightly lighter band for separation)
  doc.rect(4, 0, PAGE_W - 4, 80).fill(C.zinc800);

  // Logo / brand
  doc
    .fillColor(C.white)
    .font('Helvetica-Bold')
    .fontSize(15)
    .text('COLYTICS AI', ML, 22, { width: CONTENT_W / 2 });

  doc.fillColor(C.gold).font('Helvetica').fontSize(9).text('Intelligence Platform', ML, 40);

  // Report title (right side)
  doc
    .fillColor(C.white)
    .font('Helvetica-Bold')
    .fontSize(13)
    .text(title, PAGE_W / 2, 20, { width: PAGE_W / 2 - MR, align: 'right' });

  doc
    .fillColor(C.zinc400)
    .font('Helvetica')
    .fontSize(9)
    .text(subtitle, PAGE_W / 2, 38, { width: PAGE_W / 2 - MR, align: 'right' });

  doc
    .fillColor(C.zinc500)
    .font('Helvetica')
    .fontSize(8)
    .text(`Domain: ${domain}`, PAGE_W / 2, 54, { width: PAGE_W / 2 - MR, align: 'right' });

  // Thin gold divider below header
  doc.rect(ML, 86, CONTENT_W, 1).fill(C.gold);
}

function drawFooter(doc: PDFKit.PDFDocument, pageNum: number) {
  const y = PAGE_H - 30;
  doc.rect(0, PAGE_H - 36, PAGE_W, 36).fill(C.zinc900);
  doc
    .fillColor(C.zinc500)
    .font('Helvetica')
    .fontSize(7.5)
    .text(
      `Generated by Colytics AI  •  ${new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}`,
      ML,
      y,
      { width: CONTENT_W - 40 },
    );
  doc.fillColor(C.zinc400).fontSize(7.5).text(`Page ${pageNum}`, PAGE_W - MR - 30, y, { width: 30, align: 'right' });
}

// ─── Section label ────────────────────────────────────────────────────────────

function sectionLabel(doc: PDFKit.PDFDocument, label: string, y: number) {
  doc.rect(ML, y, 3, 12).fill(C.gold);
  doc.fillColor(C.white).font('Helvetica-Bold').fontSize(10).text(label, ML + 10, y + 1);
  return y + 22;
}

// ─── KPI cards row ────────────────────────────────────────────────────────────

function drawKpiRow(
  doc: PDFKit.PDFDocument,
  y: number,
  items: Array<{ label: string; value: string | number; sub?: string; color?: string }>,
) {
  const colW = CONTENT_W / items.length;
  items.forEach((item, i) => {
    const x = ML + i * colW;
    const color = item.color ?? C.gold;
    // Card fill (slightly lighter than page for visual separation)
    doc.roundedRect(x + 2, y, colW - 6, 54, 5).fill(C.zinc800);
    // Top accent
    doc.rect(x + 2, y, colW - 6, 2).fill(color);
    // Value — truncate to 12 chars, scale font for length
    const rawVal = String(item.value);
    const valDisplay = rawVal.length > 12 ? rawVal.slice(0, 11) + '\u2026' : rawVal;
    const valFontSize = valDisplay.length > 8 ? 14 : valDisplay.length > 5 ? 18 : 22;
    doc.fillColor(color).font('Helvetica-Bold').fontSize(valFontSize)
      .text(valDisplay, x + 6, y + 10, { width: colW - 14, align: 'center', lineBreak: false });
    // Label
    doc.fillColor(C.zinc300).font('Helvetica').fontSize(7.5)
      .text(item.label, x + 6, y + 38, { width: colW - 14, align: 'center', lineBreak: false });
    if (item.sub) {
      doc.fillColor(C.zinc500).fontSize(7).text(item.sub, x + 10, y + 43, { width: colW - 20, align: 'center' });
    }
  });
  return y + 63;
}

// ─── Horizontal bar chart ─────────────────────────────────────────────────────

function drawHBarChart(
  doc: PDFKit.PDFDocument,
  y: number,
  bars: Array<{ label: string; value: number; max: number; color?: string }>,
  height = 18,
  gap = 6,
) {
  const chartW = CONTENT_W - 100;
  const labelW = 96;
  let cy = y;
  bars.forEach((bar) => {
    const pct = Math.min(1, bar.value / bar.max);
    const fillW = pct * chartW;
    const color = bar.color ?? C.gold;

    // Label
    doc.fillColor(C.zinc400).font('Helvetica').fontSize(8).text(bar.label, ML, cy + 4, { width: labelW });

    // Background track
    doc.rect(ML + labelW, cy, chartW, height).fill(C.zinc800);
    // Fill
    if (fillW > 0) {
      doc.rect(ML + labelW, cy, fillW, height).fill(color);
    }
    // Value text
    doc
      .fillColor(C.white)
      .font('Helvetica-Bold')
      .fontSize(8)
      .text(`${Math.round(bar.value)}`, ML + labelW + fillW + 4, cy + 4);

    cy += height + gap;
  });
  return cy + 4;
}

// ─── Vertical bar chart  ─────────────────────────────────────────────────────

function drawVBarChart(
  doc: PDFKit.PDFDocument,
  y: number,
  bars: Array<{ label: string; value: number }>,
  maxVal: number,
  chartH = 80,
  colors?: string[],
) {
  const BAR_W = Math.min(30, (CONTENT_W - 20) / bars.length - 6);
  const totalW = bars.length * (BAR_W + 6) - 6;
  const startX = ML + (CONTENT_W - totalW) / 2;

  bars.forEach((bar, i) => {
    const x = startX + i * (BAR_W + 6);
    const fillH = maxVal > 0 ? (bar.value / maxVal) * chartH : 0;
    const color = colors?.[i % (colors?.length ?? 1)] ?? C.gold;
    const barY = y + chartH - fillH;

    // Background
    doc.rect(x, y, BAR_W, chartH).fill(C.zinc800);
    // Fill
    if (fillH > 0) {
      doc.rect(x, barY, BAR_W, fillH).fill(color);
    }
    // Value
    if (bar.value > 0) {
      doc
        .fillColor(C.white)
        .font('Helvetica-Bold')
        .fontSize(7)
        .text(String(Math.round(bar.value)), x, barY - 10, { width: BAR_W, align: 'center' });
    }
    // Label
    doc
      .fillColor(C.zinc400)
      .font('Helvetica')
      .fontSize(7)
      .text(bar.label, x - 4, y + chartH + 4, { width: BAR_W + 8, align: 'center' });
  });
  return y + chartH + 22;
}

// ─── Donut / gauge  ──────────────────────────────────────────────────────────

function drawScoreGauge(doc: PDFKit.PDFDocument, cx: number, cy: number, score: number | null, label: string, color: string) {
  const r = 34;
  const val = score ?? 0;
  // Outer ring (track)
  doc.circle(cx, cy, r).lineWidth(7).strokeColor(C.zinc800).stroke();
  // Score arc (simulate with overlapping fill — pdfkit arc via bezier)
  // We'll use a simple arc technique using strokeColor
  if (val > 0) {
    // pdfkit doesn't have direct arc(), use path
    const startAngle = -Math.PI / 2;
    const sweepAngle = (val / 100) * 2 * Math.PI;
    const endAngle = startAngle + sweepAngle;

    doc
      .path(arcPath(cx, cy, r, startAngle, endAngle))
      .lineWidth(7)
      .strokeColor(color)
      .stroke();
  }
  // Center text
  doc
    .fillColor(color)
    .font('Helvetica-Bold')
    .fontSize(16)
    .text(score !== null ? `${score}` : 'N/A', cx - r, cy - 10, { width: r * 2, align: 'center' });
  doc
    .fillColor(C.zinc400)
    .font('Helvetica')
    .fontSize(7)
    .text(label, cx - r, cy + 10, { width: r * 2, align: 'center' });
}

function arcPath(cx: number, cy: number, r: number, startAngle: number, endAngle: number): string {
  // Create SVG-style arc path
  const x1 = cx + r * Math.cos(startAngle);
  const y1 = cy + r * Math.sin(startAngle);
  const x2 = cx + r * Math.cos(endAngle);
  const y2 = cy + r * Math.sin(endAngle);
  const largeArc = endAngle - startAngle > Math.PI ? 1 : 0;
  return `M ${x1} ${y1} A ${r} ${r} 0 ${largeArc} 1 ${x2} ${y2}`;
}

// ─── Simple table ─────────────────────────────────────────────────────────────

function drawTable(
  doc: PDFKit.PDFDocument,
  y: number,
  headers: string[],
  rows: string[][],
  colWidths?: number[],
  maxRows = 20,
) {
  const widths = colWidths ?? headers.map(() => CONTENT_W / headers.length);
  const ROW_H = 18;

  // Header row
  doc.rect(ML, y, CONTENT_W, ROW_H).fill(C.zinc800);
  let hx = ML;
  headers.forEach((h, i) => {
    doc.fillColor(C.gold).font('Helvetica-Bold').fontSize(8).text(h, hx + 4, y + 5, { width: widths[i] - 8 });
    hx += widths[i];
  });
  y += ROW_H;

  // Data rows
  const displayRows = rows.slice(0, maxRows);
  displayRows.forEach((row, ri) => {
    const bg = ri % 2 === 0 ? C.zinc900 : '#16161A';
    doc.rect(ML, y, CONTENT_W, ROW_H).fill(bg);
    let rx = ML;
    row.forEach((cell, ci) => {
      doc.fillColor(C.zinc300).font('Helvetica').fontSize(7.5).text(cell, rx + 4, y + 5, { width: widths[ci] - 8 });
      rx += widths[ci];
    });
    y += ROW_H;
  });

  if (rows.length > maxRows) {
    doc.fillColor(C.zinc500).font('Helvetica').fontSize(7).text(`…and ${rows.length - maxRows} more`, ML, y + 3);
    y += 14;
  }

  return y + 8;
}

// ─── Severity badge text ─────────────────────────────────────────────────────

function badgeColor(severity: string): string {
  if (severity === 'critical') return C.red;
  if (severity === 'warning') return C.amber;
  return C.blue;
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── WEEKLY SUMMARY PDF ──────────────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildWeeklySummaryPdf(jobId: string, domain: string, reportData?: any): Promise<Buffer> {
  const db = await connectToMongo();
  const jobRepo = new JobRepository();

  let aivsScore: number | null = null;
  let aivsDelta: number | null = null;
  let healthScore: number | null = null;
  let healthDelta: number | null = null;
  let citations: number | null = null;
  let citationDelta: number | null = null;
  let sov: number | null = null;
  let sovDelta: number | null = null;
  let pagesCrawled: number | null = null;
  let crawlDate = 'N/A';
  let modelScores: Array<{ label: string; value: number }> = [];
  let sovHistory: Array<{ label: string; value: number }> = [];
  let topActionsRaw: any[] = [];
  let wins: any[] = [];
  let losses: any[] = [];
  let topPages: any[] = [];

  if (reportData) {
    // ── Use existing report data ──────────────────────────────────────────
    aivsScore = reportData.aivs_score;
    aivsDelta = reportData.aivs_delta;
    healthScore = reportData.health_score;
    healthDelta = reportData.health_delta;
    citations = reportData.citation_count;
    citationDelta = reportData.citation_delta;
    sov = reportData.sov_percent;
    sovDelta = reportData.sov_delta;
    wins = reportData.wins || [];
    losses = reportData.losses || [];
    topPages = reportData.top_pages || [];

    const job = await db.collection('jobs').findOne({ id: jobId }, { projection: { total_pages: 1, completedAt: 1 } });
    pagesCrawled = (job as any)?.total_pages ?? null;
    crawlDate = (job as any)?.completedAt
      ? new Date((job as any).completedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
      : 'N/A';
  } else {
    // ── Fetch data in parallel (Legacy / General Export) ──────────────────
    // effectiveId is the crawl job — used for fields/pages/job_summaries
    const effectiveId = await jobRepo.resolveEffectiveJobId(jobId);
    // allJobIds includes AEO_ANALYSIS, MODULE_E_* etc. — needed for module_c/module_e
    const allJobIds = await resolveAllProjectJobIds(db, jobId);

    const [aivsDoc, pageStats, moduleE, jobSummary, topActions] = await Promise.all([
      db.collection('module_c').findOne(
        { jobId: { $in: allJobIds } },
        { projection: { overall_score: 1, modules: 1 }, sort: { timestamp: -1 } } as any,
      ),
      db.collection('fields').aggregate([
        { $match: { jobId: effectiveId } },
        { $group: { _id: null, avg_health: { $avg: { $ifNull: ['$recommendations.health_score', 100] } }, total: { $sum: 1 } } },
      ]).toArray(),
      db.collection('module_e').findOne(
        { jobId: { $in: allJobIds } },
        { projection: { brand_analysis: 1, ai_share_of_voice: 1, ai_sov_history: 1, master_analysis: 1 } },
      ),
      db.collection('job_summaries').findOne({ jobId: effectiveId }, { projection: { total_pages: 1, completed_at: 1 } }),
      db.collection('fields').aggregate([
        { $match: { jobId: effectiveId } },
        { $unwind: { path: '$recommendations.recommendations', preserveNullAndEmptyArrays: false } },
        { $group: { _id: '$recommendations.recommendations.title', title: { $first: '$recommendations.recommendations.title' }, severity: { $first: '$recommendations.recommendations.severity' }, category: { $first: '$recommendations.recommendations.category' }, count: { $sum: 1 } } },
        { $addFields: { order: { $switch: { branches: [{ case: { $eq: ['$severity', 'critical'] }, then: 1 }, { case: { $eq: ['$severity', 'warning'] }, then: 2 }], default: 3 } } } },
        { $sort: { order: 1, count: -1 } },
        { $limit: 8 },
      ]).toArray(),
    ]);

    aivsScore = typeof aivsDoc?.overall_score === 'number' ? Math.round(aivsDoc.overall_score) : null;
    healthScore = pageStats[0]?.avg_health != null ? Math.round(pageStats[0].avg_health) : null;
    citations = (moduleE as any)?.brand_analysis?.total_mentions ?? null;
    sov = (moduleE as any)?.ai_share_of_voice?.overall_sov ?? null;
    pagesCrawled = (jobSummary as any)?.total_pages ?? null;
    crawlDate = (jobSummary as any)?.completed_at
      ? new Date((jobSummary as any).completed_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
      : 'N/A';
    topActionsRaw = topActions;

    // Model-wise scores from module_e master_analysis
    const masterModels: any[] = (moduleE as any)?.master_analysis?.models ?? [];
    masterModels.forEach((m: any) => {
      if (typeof m.model === 'string' && typeof m.model_wise_performance_score === 'number') {
        modelScores.push({ label: m.model.charAt(0).toUpperCase() + m.model.slice(1), value: Math.round(m.model_wise_performance_score) });
      }
    });

    // SOV history for trend
    sovHistory = ((moduleE as any)?.ai_sov_history ?? [])
      .slice(-6)
      .map((h: any) => ({
        label: h.date ? new Date(h.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : '',
        value: typeof h.overall_sov === 'number' ? Math.round(h.overall_sov) : 0,
      }));
  }

  // Helper for delta text
  const fmtDelta = (d: number | null | undefined) => {
    if (d == null || d === 0) return '';
    return `${d > 0 ? '+' : ''}${d.toFixed(1)}`;
  };

  // ── Build PDF ───────────────────────────────────────────────────────────
  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'Weekly Summary Report', Author: 'Colytics AI' } });

  drawPageHeader(doc, 'Weekly Summary', `Report Date: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`, domain);

  let y = 102;

  // ── KPI Section ──────────────────────────────────────────────────────────
  y = sectionLabel(doc, 'KEY PERFORMANCE INDICATORS', y);
  y = drawKpiRow(doc, y, [
    { label: 'AI Visibility Score', value: aivsScore !== null ? aivsScore : 'N/A', sub: aivsDelta ? `${fmtDelta(aivsDelta)} vs prior` : '', color: C.gold },
    { label: 'Website Health', value: healthScore !== null ? `${healthScore}%` : 'N/A', sub: healthDelta ? `${fmtDelta(healthDelta)} vs prior` : '', color: C.emerald },
    { label: 'Total Citations', value: citations !== null ? citations : '—', sub: citationDelta ? `${fmtDelta(citationDelta)} vs prior` : '', color: C.blue },
    { label: 'Share of Voice', value: sov !== null ? `${sov.toFixed(1)}%` : '—', sub: sovDelta ? `${fmtDelta(sovDelta)} vs prior` : '', color: C.purple },
  ]);

  y += 6;

  // ── Wins & Losses Section (If data available) ───────────────────────────
  if (wins.length > 0 || losses.length > 0) {
    y = sectionLabel(doc, 'TOP WINS & LOSSES', y);
    const rows: string[][] = [];
    wins.slice(0, 3).forEach(w => rows.push([w.metric, w.model, `${w.previous.toFixed(1)}`, `${w.current.toFixed(1)}`, `+${w.delta.toFixed(1)} (WIN)`]));
    losses.slice(0, 3).forEach(l => rows.push([l.metric, l.model, `${l.previous.toFixed(1)}`, `${l.current.toFixed(1)}`, `${l.delta.toFixed(1)} (LOSS)`]));

    if (rows.length > 0) {
      y = drawTable(doc, y, ['Metric', 'Model', 'Prev', 'Now', 'Change'], rows, [180, 80, 60, 60, 90]);
      y += 8;
    }
  }

  // ── Top Cited Pages ──────────────────────────────────────────────────────
  if (topPages.length > 0) {
    y = sectionLabel(doc, 'TOP CITED PAGES', y);
    const rows = topPages.slice(0, 5).map(p => [
      p.url,
      String(p.citations),
      p.primary_model || '—',
    ]);
    y = drawTable(doc, y, ['Page URL', 'Citations', 'Primary Model'], rows, [320, 80, 70]);
    y += 8;
  }

  // ── AIVS Gauge + Model breakdown ──────────────────────────────────────────
  if (aivsScore !== null) {
    y = sectionLabel(doc, 'AI VISIBILITY — MODEL BREAKDOWN', y);

    if (modelScores.length > 0) {
      const maxScore = 100;
      y = drawHBarChart(doc, y, modelScores.map(m => ({ label: m.label, value: m.value, max: maxScore, color: C.gold })));
    } else {
      // Single gauge
      drawScoreGauge(doc, ML + 60, y + 50, aivsScore, 'AIVS Score', C.gold);
      y += 110;
    }
  }

  y += 6;

  // ── SOV trend ────────────────────────────────────────────────────────────
  if (sovHistory.length >= 2) {
    y = sectionLabel(doc, 'SHARE OF VOICE — TREND (LAST 6 PERIODS)', y);
    y = drawVBarChart(doc, y, sovHistory, 100, 70, [C.gold, C.goldLight, C.amber, C.gold, C.goldLight, C.amber]);
  }

  // ── Crawl stats ───────────────────────────────────────────────────────────
  y = sectionLabel(doc, 'CRAWL SUMMARY', y);
  y = drawKpiRow(doc, y, [
    { label: 'Pages Crawled', value: pagesCrawled !== null ? pagesCrawled : 'N/A', color: C.zinc300 },
    { label: 'Last Crawl', value: crawlDate, color: C.zinc300 },
    { label: 'Domain', value: domain, color: C.zinc300 },
    { label: 'Report Period', value: 'Weekly', color: C.zinc300 },
  ]);

  y += 8;

  // ── Top Actions ───────────────────────────────────────────────────────────
  if (topActionsRaw.length > 0) {
    y = sectionLabel(doc, 'TOP PRIORITY ACTIONS', y);
    const rows = topActionsRaw.map((a: any) => [
      a.title ?? '',
      `${a.category ?? ''}`,
      `${a.severity ?? ''}`.toUpperCase(),
      String(a.count ?? 0),
    ]);
    y = drawTable(doc, y, ['Action', 'Category', 'Severity', 'Pages'], rows, [220, 110, 80, 60]);
  }

  drawFooter(doc, 1);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── AUDIT REPORT PDF ────────────────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildAuditReportPdf(jobId: string, userId: string, domain: string): Promise<Buffer> {
  const auditService = new AuditReportsService();
  const report = await auditService.getReport(userId, jobId);

  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'Audit Report', Author: 'Colytics AI' } });

  const title = 'Technical Audit Report';
  const subtitle = `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`;
  drawPageHeader(doc, title, subtitle, domain);

  let y = 102;

  // ── Summary scorecards ────────────────────────────────────────────────────
  y = sectionLabel(doc, 'AUDIT SUMMARY', y);
  const s = report.report.summary;
  y = drawKpiRow(doc, y, [
    { label: 'Critical Issues', value: s.critical, color: C.red },
    { label: 'Warnings', value: s.warning, color: C.amber },
    { label: 'Total Issues', value: s.total, color: C.zinc400 },
    { label: 'Info', value: s.info, color: C.blue },
  ]);

  y += 8;

  // ── Issues bar chart (by severity) ───────────────────────────────────────
  y = sectionLabel(doc, 'ISSUES BY SEVERITY', y);
  y = drawHBarChart(doc, y, [
    { label: 'Critical', value: s.critical, max: Math.max(s.total, 1), color: C.red },
    { label: 'Warning', value: s.warning, max: Math.max(s.total, 1), color: C.amber },
    { label: 'Info', value: s.info, max: Math.max(s.total, 1), color: C.blue },
  ]);

  y += 8;

  // ── Issues by category ────────────────────────────────────────────────────
  const categories: Record<string, { critical: number; warning: number; info: number }> = {};
  report.report.issues.forEach((issue) => {
    if (!categories[issue.category]) categories[issue.category] = { critical: 0, warning: 0, info: 0 };
    categories[issue.category][issue.severity]++;
  });

  if (Object.keys(categories).length > 0) {
    y = sectionLabel(doc, 'ISSUES BY CATEGORY', y);
    const catRows = Object.entries(categories).map(([cat, counts]) => [
      cat.replace(/_/g, ' ').toUpperCase(),
      String(counts.critical),
      String(counts.warning),
      String(counts.info),
    ]);
    y = drawTable(doc, y, ['Category', 'Critical', 'Warning', 'Info'], catRows, [200, 100, 100, 70]);
  }

  y += 6;

  // ── Detailed issues list ──────────────────────────────────────────────────
  y = sectionLabel(doc, 'ISSUE DETAILS', y);

  const PAGE_BREAK_Y = PAGE_H - 60;
  let pageNum = 1;

  report.report.issues.forEach((issue) => {
    if (y > PAGE_BREAK_Y) {
      drawFooter(doc, pageNum);
      doc.addPage({ size: 'A4', margin: 0 });
      pageNum++;
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }

    // Issue card header
    const color = badgeColor(issue.severity);
    doc.rect(ML, y, CONTENT_W, 2).fill(color);
    y += 4;

    doc.fillColor(color).font('Helvetica-Bold').fontSize(9).text(`[${issue.severity.toUpperCase()}] ${issue.title}`, ML, y);
    y += 13;
    doc.fillColor(C.zinc300).font('Helvetica').fontSize(8).text(issue.description, ML + 4, y, { width: CONTENT_W - 8 });
    y += doc.heightOfString(issue.description, { width: CONTENT_W - 8 }) + 4;

    doc.fillColor(C.zinc500).fontSize(7.5).text(`Affected: ${issue.affected_count} pages`, ML + 4, y);
    y += 11;

    if (issue.fix) {
      doc.fillColor(C.emerald).fontSize(7.5).text(`Fix: ${issue.fix}`, ML + 4, y, { width: CONTENT_W - 8 });
      y += doc.heightOfString(issue.fix, { width: CONTENT_W - 8 }) + 4;
    }

    if (issue.example_urls.length > 0) {
      doc.fillColor(C.zinc500).fontSize(6.5).text(`Examples: ${issue.example_urls.slice(0, 2).join('  •  ')}`, ML + 4, y, { width: CONTENT_W - 8 });
      y += 10;
    }

    y += 6;
  });

  drawFooter(doc, pageNum);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── COMPETITOR REPORT PDF ───────────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════════════════
// ── SERP ANALYSIS REPORT PDF (Module A) ─────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildSerpAnalysisPdf(jobId: string, domain: string): Promise<Buffer> {
  const db = await connectToMongo();
  const jobRepo = new JobRepository();
  const effectiveId = await jobRepo.resolveEffectiveJobId(jobId);

  const serpDoc = await db.collection('serp_results').findOne({ jobId: effectiveId }) as any;

  const summary = serpDoc?.summary ?? {};
  const keywords: any[] = serpDoc?.keyword_results ?? [];
  const contentGaps: any[] = serpDoc?.content_gaps ?? [];
  const volatility = serpDoc?.volatility ?? {};
  const featureFreq: Record<string, number> = summary?.feature_frequency ?? {};

  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'SERP Analysis Report', Author: 'Colytics AI' } });
  const title = 'SERP Analysis Report';
  const subtitle = `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`;
  drawPageHeader(doc, title, subtitle, domain);
  let y = 102;
  let pageNum = 1;
  const PAGE_BREAK_Y = PAGE_H - 60;

  // ── KPI Summary ─────────────────────────────────────────────────────────
  y = sectionLabel(doc, 'KEYWORD RANKING OVERVIEW', y);
  y = drawKpiRow(doc, y, [
    { label: 'Total Keywords', value: summary.total_keywords ?? 0, color: C.zinc300 },
    { label: 'Ranked', value: summary.ranked_keywords ?? 0, color: C.emerald },
    { label: 'Unranked', value: summary.unranked_keywords ?? 0, color: C.red },
    { label: 'Avg Rank', value: summary.avg_rank != null ? `#${Math.round(summary.avg_rank)}` : 'N/A', color: C.gold },
  ]);

  y += 4;
  y = drawKpiRow(doc, y, [
    { label: 'Top 3', value: summary.top3 ?? 0, color: C.emerald },
    { label: 'Top 10', value: summary.top10 ?? 0, color: C.gold },
    { label: 'Top 20', value: summary.top20 ?? 0, color: C.amber },
    { label: 'Top 100', value: summary.top100 ?? 0, color: C.zinc400 },
  ]);

  y += 8;

  // ── Rank distribution bar chart ──────────────────────────────────────────
  if (summary.top3 != null || summary.top10 != null) {
    y = sectionLabel(doc, 'RANK DISTRIBUTION', y);
    const maxVal = summary.ranked_keywords || 1;
    y = drawHBarChart(doc, y, [
      { label: 'Top 3', value: summary.top3 ?? 0, max: maxVal, color: C.emerald },
      { label: 'Top 10', value: summary.top10 ?? 0, max: maxVal, color: C.gold },
      { label: 'Top 20', value: summary.top20 ?? 0, max: maxVal, color: C.amber },
      { label: 'Top 100', value: summary.top100 ?? 0, max: maxVal, color: C.zinc400 },
    ]);
    y += 4;
  }

  // ── SERP Volatility ───────────────────────────────────────────────────────
  y = sectionLabel(doc, 'SERP VOLATILITY', y);
  const volColor = volatility.level === 'stable' ? C.emerald : volatility.level === 'medium' ? C.amber : C.red;
  y = drawKpiRow(doc, y, [
    { label: 'Volatility Level', value: (volatility.level ?? 'N/A').toUpperCase(), color: volColor },
    { label: 'Volatility Score', value: volatility.score != null ? volatility.score.toFixed(1) : 'N/A', color: volColor },
    { label: 'Rank Std Dev', value: volatility.rank_std_dev != null ? volatility.rank_std_dev.toFixed(1) : 'N/A', color: C.zinc400 },
    { label: 'Location', value: serpDoc?.location_code ?? 'Global', color: C.zinc300 },
  ]);

  y += 8;

  // ── SERP Feature Frequency ────────────────────────────────────────────────
  const featureEntries = Object.entries(featureFreq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8);
  if (featureEntries.length > 0) {
    y = sectionLabel(doc, 'SERP FEATURES DETECTED', y);
    const maxFeature = featureEntries[0][1] || 1;
    y = drawHBarChart(doc, y, featureEntries.map(([k, v]) => ({
      label: k.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
      value: v,
      max: maxFeature,
      color: C.blue,
    })));
    y += 4;
  }

  // ── Keyword Detail Table ──────────────────────────────────────────────────
  if (keywords.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, `KEYWORD RANKINGS (${Math.min(keywords.length, 30)} of ${keywords.length})`, y);
    const kwRows = keywords.slice(0, 30).map((k: any) => [
      k.keyword ?? '',
      k.target_rank != null ? `#${k.target_rank}` : '—',
      k.target_title ? k.target_title.substring(0, 40) : '—',
      String(k.paa_questions?.length ?? 0),
      k.features ? Object.keys(k.features).filter(f => (k.features[f] as any)?.present).join(', ') || '—' : '—',
    ]);
    y = drawTable(doc, y, ['Keyword', 'Rank', 'Ranking Title', 'PAA Qs', 'SERP Features'], kwRows, [150, 40, 160, 40, 100], 30);
    y += 8;
  }

  // ── Content Gap Opportunities ─────────────────────────────────────────────
  if (contentGaps.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, `CONTENT GAP OPPORTUNITIES (${contentGaps.length})`, y);
    const gapRows = contentGaps.slice(0, 20).map((g: any) => [
      g.keyword ?? '',
      g.opportunity_type === 'not_ranking' ? 'Not Ranking' : 'Low Ranking',
      g.target_rank != null ? `#${g.target_rank}` : '—',
      g.has_featured_snippet ? 'Yes' : 'No',
      g.has_paa ? 'Yes' : 'No',
      g.top_ranking_domain ?? '—',
    ]);
    y = drawTable(
      doc, y,
      ['Keyword', 'Gap Type', 'Current Rank', 'Featured Snip.', 'PAA', 'Top Ranker'],
      gapRows, [140, 80, 65, 65, 40, 100], 20,
    );
    y += 8;
  }

  // ── People Also Ask Summary ───────────────────────────────────────────────
  const allPaa: Array<{ question: string; keyword: string }> = [];
  keywords.forEach((k: any) => {
    (k.paa_questions ?? []).forEach((q: any) => {
      allPaa.push({ question: q.question ?? q, keyword: k.keyword ?? '' });
    });
  });
  if (allPaa.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, `PEOPLE ALSO ASK — KEY QUESTIONS (${Math.min(allPaa.length, 15)})`, y);
    allPaa.slice(0, 15).forEach((item, i) => {
      if (y > PAGE_BREAK_Y) {
        drawFooter(doc, pageNum++);
        doc.addPage({ size: 'A4', margin: 0 });
        drawPageHeader(doc, title, subtitle, domain);
        y = 102;
      }
      doc.fillColor(C.gold).font('Helvetica-Bold').fontSize(8).text(`${i + 1}.`, ML, y, { width: 16 });
      doc.fillColor(C.zinc300).font('Helvetica').fontSize(8).text(item.question, ML + 18, y, { width: CONTENT_W - 80 });
      doc.fillColor(C.zinc500).fontSize(7).text(`[${item.keyword}]`, ML + CONTENT_W - 60, y, { width: 60, align: 'right' });
      y += 14;
    });
  }

  drawFooter(doc, pageNum);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── COMPETITOR AI INTELLIGENCE REPORT PDF (Module F) ────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildCompetitorAiReportPdf(jobId: string, domain: string): Promise<Buffer> {
  const db = await connectToMongo();
  const jobRepo = new JobRepository();
  const effectiveId = await jobRepo.resolveEffectiveJobId(jobId);
  const allJobIds = await resolveAllProjectJobIds(db, jobId);

  // module_f can be under effectiveId or any of the project's job IDs
  const fDoc: any = await (async () => {
    const direct = await db.collection('module_f').findOne({
      jobId: effectiveId,
      compare_visibility_against_competitors: { $exists: true },
    });
    if (direct) return direct;
    return db.collection('module_f').findOne({ jobId: { $in: allJobIds } });
  })();

  const compareVis = fDoc?.compare_visibility_against_competitors ?? {};
  const brandData = compareVis.brand ?? null;
  const competitors: any[] = compareVis.competitors ?? [];
  const compWins = fDoc?.competitor_wins ?? {};
  const gapOps: any[] = fDoc?.gap_opportunities ?? fDoc?.gap_analysis ?? [];
  const srcAnalysis: any[] = fDoc?.source_analysis?.competitor_source_analysis ?? [];
  const emergingTrends = fDoc?.emerging_trends ?? {};
  const moat4 = fDoc?.moat4_recommendations ?? {};
  const metricRecs: Record<string, any> = fDoc?.recommendations ?? fDoc?.metric_recommendations ?? {};
  const topPagesData: any[] = fDoc?.top_pages ?? [];

  // Fetch trend history from module_e
  const moduleE = await db.collection('module_e').findOne({ jobId: { $in: allJobIds } });
  const sovHistory: any[] = (moduleE as any)?.ai_sov_history ?? [];

  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'Competitor AI Intelligence', Author: 'Colytics AI' } });
  const title = 'Competitor AI Intelligence Report';
  const subtitle = `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`;
  drawPageHeader(doc, title, subtitle, domain);
  let y = 102;
  let pageNum = 1;
  const PAGE_BREAK_Y = PAGE_H - 60;

  // ── Brand vs. Market KPIs ─────────────────────────────────────────────────
  y = sectionLabel(doc, 'BRAND VISIBILITY OVERVIEW', y);
  y = drawKpiRow(doc, y, [
    { label: 'Brand Visibility Score', value: brandData ? `${Math.round(brandData.visibility_score ?? 0)}` : 'N/A', color: C.gold },
    { label: 'Market Share', value: brandData ? `${(brandData.market_share_percent ?? 0).toFixed(1)}%` : 'N/A', color: C.blue },
    { label: 'Total Mentions', value: brandData?.mentions_total ?? 'N/A', color: C.emerald },
    { label: 'Models Tracking', value: brandData?.mentioned_in_models ?? compareVis.models?.length ?? 'N/A', color: C.zinc300 },
  ]);

  y += 8;

  // ── Wins vs Losses Summary ────────────────────────────────────────────────
  if (compWins?.summary) {
    y = sectionLabel(doc, 'CONTENT WINS vs LOSSES', y);
    const ws = compWins.summary;
    y = drawKpiRow(doc, y, [
      { label: 'Brand Wins', value: ws.brand_wins ?? 0, color: C.emerald },
      { label: 'Competitor Wins', value: ws.competitor_wins ?? 0, color: C.red },
      { label: 'Win Rate', value: ws.brand_win_rate != null ? `${(ws.brand_win_rate * 100).toFixed(1)}%` : 'N/A', color: C.gold },
      { label: 'Avg Content Gap', value: ws.avg_content_gap_score != null ? ws.avg_content_gap_score.toFixed(1) : 'N/A', color: C.amber },
    ]);
    y += 8;

    // Win/Loss prompt table
    if (compWins.detailed_results?.length > 0) {
      if (y > PAGE_BREAK_Y - 40) {
        drawFooter(doc, pageNum++);
        doc.addPage({ size: 'A4', margin: 0 });
        drawPageHeader(doc, title, subtitle, domain);
        y = 102;
      }
      y = sectionLabel(doc, 'WIN / LOSS PROMPT BREAKDOWN', y);
      const wlRows = (compWins.detailed_results as any[]).slice(0, 15).map((r: any) => [
        r.prompt ? r.prompt.substring(0, 45) : '—',
        r.winner === 'brand' ? 'WIN' : r.winner === 'competitor' ? 'LOSS' : r.winner?.toUpperCase() ?? '—',
        r.winner_name ?? '—',
        r.brand_rank != null ? `#${r.brand_rank}` : '—',
        r.coverage_gap_score != null ? r.coverage_gap_score.toFixed(1) : '—',
      ]);
      y = drawTable(doc, y, ['Prompt', 'Result', 'Winner', 'Brand Rank', 'Gap Score'], wlRows, [160, 45, 100, 65, 60], 15);
      y += 8;
    }
  }

  // ── Competitor Visibility Comparison ──────────────────────────────────────
  if (competitors.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'COMPETITOR VISIBILITY COMPARISON', y);

    // Horizontal bar chart (visibility scores)
    const allPlayers = [
      ...(brandData ? [{ label: 'YOUR BRAND', value: Math.round(brandData.visibility_score ?? 0) }] : []),
      ...competitors.slice(0, 8).map((c: any) => ({
        label: c.name ? c.name.substring(0, 20) : 'Competitor',
        value: Math.round(c.visibility_score ?? 0),
      })),
    ];
    y = drawHBarChart(doc, y, allPlayers.map(p => ({
      label: p.label,
      value: p.value,
      max: 100,
      color: p.label === 'YOUR BRAND' ? C.gold : C.blue,
    })));
    y += 4;

    // Competitor detail table
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'COMPETITOR METRICS TABLE', y);
    const compRows = competitors.slice(0, 12).map((c: any) => [
      c.name ?? '—',
      Math.round(c.visibility_score ?? 0).toString(),
      `${(c.market_share_percent ?? 0).toFixed(1)}%`,
      String(c.mentions_total ?? 0),
      c.avg_rank != null ? `#${Math.round(c.avg_rank)}` : '—',
      c.rank_difference_vs_brand != null
        ? (c.rank_difference_vs_brand > 0 ? `+${c.rank_difference_vs_brand}` : String(c.rank_difference_vs_brand))
        : '—',
    ]);
    y = drawTable(
      doc, y,
      ['Competitor', 'Visibility', 'Mkt Share', 'Mentions', 'Avg Rank', 'Rank Diff'],
      compRows, [160, 55, 65, 60, 55, 55], 12,
    );
    y += 8;
  }

  // ── Growth Trend Chart ────────────────────────────────────────────────────
  if (sovHistory.length >= 2) {
    if (y > PAGE_BREAK_Y - 100) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'GROWTH TREND (AI SHARE OF VOICE %)', y);
    const trendBars = sovHistory.slice(-8).map((h: any) => ({
      label: h.date ? new Date(h.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : '—',
      value: typeof h.overall_sov === 'number' ? h.overall_sov : 0,
    }));
    const maxSov = Math.max(10, ...trendBars.map(b => b.value));
    y = drawVBarChart(doc, y, trendBars, maxSov, 80, [C.gold, C.blue, C.emerald, C.purple, C.amber]);
    y += 8;
  }

  // ── Competitor Top Pages ──────────────────────────────────────────────────
  if (topPagesData.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'COMPETITOR TOP CITED PAGES', y);
    
    topPagesData.slice(0, 5).forEach((comp: any) => {
      if (y > PAGE_BREAK_Y - 40) {
        drawFooter(doc, pageNum++);
        doc.addPage({ size: 'A4', margin: 0 });
        drawPageHeader(doc, title, subtitle, domain);
        y = 102;
      }
      doc.fillColor(C.white).font('Helvetica-Bold').fontSize(9).text(comp.name ?? '—', ML, y);
      y += 12;
      const pages = (comp.pages ?? []).slice(0, 3);
      const pageRows = pages.map((p: any) => [
        p.url ? (p.url.length > 70 ? p.url.substring(0, 67) + '...' : p.url) : '—',
        String(p.citation_count ?? 0),
        p.primary_model ?? '—',
      ]);
      y = drawTable(doc, y, ['Page URL', 'Citations', 'Primary Model'], pageRows, [340, 70, 80], 3);
      y += 6;
    });
  }

  // ── Per-Model Visibility (brand) ──────────────────────────────────────────
  if (brandData?.per_model && Object.keys(brandData.per_model).length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'BRAND PERFORMANCE PER AI MODEL', y);
    const modelRows = Object.entries(brandData.per_model as Record<string, any>).map(([model, data]: [string, any]) => [
      model.charAt(0).toUpperCase() + model.slice(1),
      String(data.mentions ?? 0),
      data.rank != null ? `#${data.rank}` : '—',
      data.rank_percentile != null ? `${Math.round(data.rank_percentile)}%` : '—',
      data.first_position != null ? `#${data.first_position}` : '—',
    ]);
    y = drawTable(doc, y, ['AI Model', 'Mentions', 'Rank', 'Rank Percentile', 'First Position'], modelRows, [130, 70, 70, 100, 100]);
    y += 8;
  }

  // ── Gap Opportunities ─────────────────────────────────────────────────────
  if (gapOps.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, `GAP OPPORTUNITIES (${gapOps.length})`, y);
    const gapRows = gapOps.slice(0, 12).map((g: any) => [
      g.competitor ?? '—',
      g.gapScore != null ? g.gapScore.toFixed(1) : '—',
      String(g.missingPrompts ?? 0),
      g.potentialGainPercent != null ? `${g.potentialGainPercent.toFixed(1)}%` : '—',
    ]);
    y = drawTable(doc, y, ['Competitor', 'Gap Score', 'Missing Prompts', 'Potential Gain'], gapRows, [200, 80, 100, 90], 12);
    y += 8;
  }

  // ── Source / Citation Analysis ────────────────────────────────────────────
  if (srcAnalysis.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'COMPETITOR SOURCE & CITATION ANALYSIS', y);
    const srcRows = srcAnalysis.slice(0, 10).map((s: any) => [
      s.competitor ?? '—',
      s.source_domain_influence_score != null ? s.source_domain_influence_score.toFixed(1) : '—',
      s.average_domain_authority != null ? Math.round(s.average_domain_authority).toString() : '—',
      String(s.citation_count ?? 0),
      (s.top_citations ?? []).slice(0, 2).map((c: any) => c.domain ?? '').filter(Boolean).join(', ') || '—',
    ]);
    y = drawTable(doc, y, ['Competitor', 'Influence Score', 'Avg DA', 'Citations', 'Top Sources'], srcRows, [150, 80, 55, 60, 125], 10);
    y += 8;
  }

  // ── Emerging Trends ───────────────────────────────────────────────────────
  if (emergingTrends?.competitor_changes?.length > 0 || emergingTrends?.summary) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'EMERGING TRENDS & MARKET SHIFTS', y);

    if (emergingTrends.summary) {
      const ts = emergingTrends.summary;
      y = drawKpiRow(doc, y, [
        { label: 'Trends Detected', value: ts.trends_detected ?? 0, color: C.blue },
        { label: 'Avg Visibility Δ', value: ts.avg_visibility_delta != null ? `${ts.avg_visibility_delta.toFixed(1)}%` : 'N/A', color: C.amber },
        { label: 'New Prompts', value: ts.new_prompts ?? 0, color: C.emerald },
        { label: 'Threat Level', value: (ts.threat_level ?? '—').toUpperCase(), color: ts.threat_level === 'high' ? C.red : ts.threat_level === 'medium' ? C.amber : C.emerald },
      ]);
      y += 8;
    }

    if (emergingTrends.competitor_changes?.length > 0) {
      const trendRows = (emergingTrends.competitor_changes as any[]).slice(0, 10).map((c: any) => [
        c.name ?? '—',
        c.status ? c.status.toUpperCase() : '—',
        c.delta_visibility != null ? `${c.delta_visibility > 0 ? '+' : ''}${c.delta_visibility.toFixed(1)}%` : '—',
        c.delta_market_share != null ? `${c.delta_market_share > 0 ? '+' : ''}${c.delta_market_share.toFixed(1)}%` : '—',
      ]);
      y = drawTable(doc, y, ['Competitor', 'Status', 'Visibility Δ', 'Market Share Δ'], trendRows, [200, 80, 90, 100], 10);
      y += 8;
    }
  }

  // ── Moat4 Recommendations (top actions) ──────────────────────────────────
  const allActions: any[] = moat4?.all_actions ?? moat4?.role_output?.actions ?? [];
  if (allActions.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, `STRATEGIC ACTION PLAN (Top ${Math.min(allActions.length, 10)})`, y);

    const sortedActions = [...allActions]
      .sort((a, b) => (b.priority_score ?? 0) - (a.priority_score ?? 0))
      .slice(0, 10);

    sortedActions.forEach((action: any, i: number) => {
      if (y > PAGE_BREAK_Y) {
        drawFooter(doc, pageNum++);
        doc.addPage({ size: 'A4', margin: 0 });
        drawPageHeader(doc, title, subtitle, domain);
        y = 102;
      }
      const urgColor = (action.urgency_score ?? 0) >= 7 ? C.red : (action.urgency_score ?? 0) >= 4 ? C.amber : C.blue;
      doc.rect(ML, y, CONTENT_W, 2).fill(urgColor);
      y += 4;
      doc.fillColor(urgColor).font('Helvetica-Bold').fontSize(8.5)
        .text(`${i + 1}. ${action.action_title ?? ''}`, ML, y, { width: CONTENT_W - 120 });
      doc.fillColor(C.zinc500).font('Helvetica').fontSize(7.5)
        .text(`Priority: ${action.priority_score ?? '—'}  Impact: ${action.impact_score ?? '—'}  Effort: ${action.effort_score ?? '—'}`,
          ML + CONTENT_W - 118, y, { width: 118, align: 'right' });
      y += 13;
      if (action.action_detail) {
        doc.fillColor(C.zinc400).font('Helvetica').fontSize(7.5)
          .text(action.action_detail, ML + 8, y, { width: CONTENT_W - 8 });
        y += doc.heightOfString(action.action_detail, { width: CONTENT_W - 8 }) + 6;
      }
    });
    y += 4;
  }

  // ── Metric Recommendations ────────────────────────────────────────────────
  const recEntries = Object.entries(metricRecs).filter(([, v]) => v);
  if (recEntries.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'METRIC-LEVEL RECOMMENDATIONS', y);
    recEntries.slice(0, 8).forEach(([metric, rec]: [string, any]) => {
      if (y > PAGE_BREAK_Y) {
        drawFooter(doc, pageNum++);
        doc.addPage({ size: 'A4', margin: 0 });
        drawPageHeader(doc, title, subtitle, domain);
        y = 102;
      }
      const metricLabel = metric.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
      doc.fillColor(C.gold).font('Helvetica-Bold').fontSize(8).text(`• ${metricLabel}`, ML, y);
      y += 12;
      const why = typeof rec === 'string' ? rec : rec?.why ?? '';
      const fix = typeof rec === 'object' ? rec?.fix ?? '' : '';
      if (why) {
        doc.fillColor(C.zinc400).font('Helvetica').fontSize(7.5).text(`Why: ${why}`, ML + 10, y, { width: CONTENT_W - 10 });
        y += doc.heightOfString(`Why: ${why}`, { width: CONTENT_W - 10 }) + 3;
      }
      if (fix) {
        doc.fillColor(C.emerald).fontSize(7.5).text(`Fix: ${fix}`, ML + 10, y, { width: CONTENT_W - 10 });
        y += doc.heightOfString(`Fix: ${fix}`, { width: CONTENT_W - 10 }) + 4;
      }
    });
  }

  drawFooter(doc, pageNum);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── AI VISIBILITY SCORECARD PDF — reimplemented with full Module C data ───────
// ═══════════════════════════════════════════════════════════════════════════════

async function buildAiScorecardPdfV2(jobId: string, domain: string): Promise<Buffer> {
  const db = await connectToMongo();
  const allJobIds = await resolveAllProjectJobIds(db, jobId);

  const [aivsDoc, moduleE] = await Promise.all([
    db.collection('module_c').findOne(
      { jobId: { $in: allJobIds } },
      { sort: { timestamp: -1 } } as any,
    ),
    db.collection('module_e').findOne(
      { jobId: { $in: allJobIds } },
      { projection: { master_analysis: 1 } },
    ),
  ]);

  const modules: any = (aivsDoc as any)?.modules ?? {};
  const aeoChecker = modules.aeo_checker ?? {};
  const entityCoverage = modules.entity_coverage ?? {};
  const answerCompleteness = modules.answer_completeness ?? {};
  const llmSim = modules.llm_simulator ?? {};
  const multiModel = modules.multi_model ?? {};
  const pageActions = modules.page_actions ?? {};
  const entityExtraction = modules.entity_extraction ?? {};
  const missingInfo = modules.missing_info ?? {};
  const modelsList: any[] = (moduleE as any)?.master_analysis?.models ?? [];
  const overallScore: number | null = typeof (aivsDoc as any)?.overall_score === 'number'
    ? Math.round((aivsDoc as any).overall_score) : null;

  const doc = new PDFDocument({ size: 'A4', margin: 0, info: { Title: 'AI Visibility Scorecard', Author: 'Colytics AI' } });
  const title = 'AI Visibility Scorecard';
  const subtitle = `Generated: ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`;
  drawPageHeader(doc, title, subtitle, domain);
  let y = 102;
  let pageNum = 1;
  const PAGE_BREAK_Y = PAGE_H - 60;

  // ── Overall + sub-scores KPIs ─────────────────────────────────────────────
  y = sectionLabel(doc, 'OVERALL AI VISIBILITY SCORE', y);
  const scoreColor = overallScore !== null ? (overallScore >= 70 ? C.emerald : overallScore >= 50 ? C.gold : C.red) : C.zinc500;
  drawScoreGauge(doc, PAGE_W / 2, y + 50, overallScore, 'AIVS Score', scoreColor);
  y += 115;

  y = sectionLabel(doc, 'MODULE SCORES', y);
  y = drawKpiRow(doc, y, [
    { label: 'LLM Friendliness', value: aeoChecker.llm_friendliness_score != null ? Math.round(aeoChecker.llm_friendliness_score) : 'N/A', color: C.gold },
    { label: 'Entity Coverage', value: entityCoverage.coverage?.entity_coverage_pct != null ? `${Math.round(entityCoverage.coverage.entity_coverage_pct)}%` : 'N/A', color: C.blue },
    { label: 'Answer Completeness', value: answerCompleteness.completeness_score != null ? Math.round(answerCompleteness.completeness_score) : 'N/A', color: C.emerald },
    { label: 'LLM Simulator', value: multiModel.overall != null ? Math.round(multiModel.overall) : 'N/A', color: C.purple },
  ]);
  y += 8;

  // ── AEO Checker sub-scores ────────────────────────────────────────────────
  if (aeoChecker.sub_scores) {
    y = sectionLabel(doc, 'LLM FRIENDLINESS BREAKDOWN', y);
    const ss = aeoChecker.sub_scores;
    const subScoreBars: Array<{ label: string; value: number; max: number; color: string }> = [
      { label: 'Crawl Access', value: ss.crawl_access?.score ?? ss.crawl_access?.weighted_score ?? 0, max: 100, color: C.blue },
      { label: 'Schema / Struct. Data', value: ss.schema?.score ?? ss.schema?.weighted_score ?? 0, max: 100, color: C.gold },
      { label: 'Content Quality', value: ss.content?.score ?? ss.content?.weighted_score ?? 0, max: 100, color: C.emerald },
      { label: 'Tech Hygiene', value: ss.tech_hygiene?.score ?? ss.tech_hygiene?.weighted_score ?? 0, max: 100, color: C.amber },
      { label: 'Structure', value: ss.structure?.score ?? ss.structure?.weighted_score ?? 0, max: 100, color: C.purple },
    ].filter(b => b.value > 0);
    if (subScoreBars.length > 0) {
      y = drawHBarChart(doc, y, subScoreBars);
      y += 4;
    }
    // Page type & topic
    if (aeoChecker.page_type || aeoChecker.page_topic) {
      doc.fillColor(C.zinc400).font('Helvetica').fontSize(8)
        .text(`Page Type: ${aeoChecker.page_type ?? '—'}   |   Topic: ${aeoChecker.page_topic ?? '—'}`, ML, y);
      y += 14;
    }
  }

  // ── Readability metrics ───────────────────────────────────────────────────
  if (aeoChecker.readability) {
    const read = aeoChecker.readability;
    y = sectionLabel(doc, 'READABILITY & CONTENT METRICS', y);
    y = drawKpiRow(doc, y, [
      { label: 'Word Count', value: entityExtraction.word_count ?? aeoChecker.word_count ?? 'N/A', color: C.zinc300 },
      { label: 'Readability Score', value: read.flesch_score != null ? Math.round(read.flesch_score) : 'N/A', color: C.blue },
      { label: 'Fog Index', value: read.fog_index != null ? read.fog_index.toFixed(1) : 'N/A', color: C.amber },
      { label: 'Avg Sentence Length', value: read.avg_sentence_length != null ? `${read.avg_sentence_length.toFixed(1)} wds` : 'N/A', color: C.zinc300 },
    ]);
    y += 8;
  }

  // ── Entity Coverage ───────────────────────────────────────────────────────
  if (y > PAGE_BREAK_Y - 40) {
    drawFooter(doc, pageNum++);
    doc.addPage({ size: 'A4', margin: 0 });
    drawPageHeader(doc, title, subtitle, domain);
    y = 102;
  }
  y = sectionLabel(doc, 'ENTITY COVERAGE ANALYSIS', y);
  y = drawKpiRow(doc, y, [
    { label: 'Coverage %', value: entityCoverage.coverage?.entity_coverage_pct != null ? `${Math.round(entityCoverage.coverage.entity_coverage_pct)}%` : 'N/A', color: C.emerald },
    { label: 'Matched Entities', value: entityCoverage.coverage?.matched_count ?? 'N/A', color: C.blue },
    { label: 'Expected Entities', value: entityCoverage.coverage?.expected_count ?? 'N/A', color: C.zinc300 },
    { label: 'Critical Missing', value: entityCoverage.critical_missing_count ?? 'N/A', color: C.red },
  ]);
  y += 6;

  const critMissing: any[] = entityCoverage.critical_missing ?? entityCoverage.missing_entities ?? [];
  if (critMissing.length > 0) {
    y = sectionLabel(doc, 'MISSING ENTITIES', y);
    const entRows = critMissing.slice(0, 12).map((e: any) => [
      typeof e === 'string' ? e : (e.name ?? '—'),
      typeof e === 'object' ? (e.type ?? '—') : '—',
      typeof e === 'object' ? ((e.importance ?? e.severity ?? '—').toUpperCase()) : '—',
    ]);
    y = drawTable(doc, y, ['Entity', 'Type', 'Importance'], entRows, [250, 120, 100], 12);
    y += 8;
  }

  // ── Answer Completeness ───────────────────────────────────────────────────
  if (y > PAGE_BREAK_Y - 40) {
    drawFooter(doc, pageNum++);
    doc.addPage({ size: 'A4', margin: 0 });
    drawPageHeader(doc, title, subtitle, domain);
    y = 102;
  }
  y = sectionLabel(doc, 'ANSWER COMPLETENESS', y);
  y = drawKpiRow(doc, y, [
    { label: 'Completeness Score', value: answerCompleteness.completeness_score != null ? Math.round(answerCompleteness.completeness_score) : 'N/A', color: C.emerald },
    { label: 'Questions Tested', value: answerCompleteness.questions_generated ?? 'N/A', color: C.zinc300 },
    { label: 'Fully Answered', value: answerCompleteness.fully_answered ?? 'N/A', color: C.emerald },
    { label: 'Not Answered', value: answerCompleteness.not_answered ?? 'N/A', color: C.red },
  ]);
  y += 6;

  const answerResults: any[] = (answerCompleteness.results ?? []).slice(0, 10);
  if (answerResults.length > 0) {
    y = sectionLabel(doc, 'QUESTION COVERAGE DETAIL', y);
    const aqRows = answerResults.map((r: any) => [
      r.question ? r.question.substring(0, 60) : '—',
      (r.status ?? '—').toUpperCase(),
      r.evidence ? r.evidence.substring(0, 60) : '—',
    ]);
    y = drawTable(doc, y, ['Question', 'Status', 'Evidence'], aqRows, [200, 70, 200], 10);
    y += 8;
  }

  // ── LLM Simulator results ─────────────────────────────────────────────────
  if (llmSim.accuracy || llmSim.consistency) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'LLM SIMULATOR — ACCURACY & CONSISTENCY', y);
    y = drawKpiRow(doc, y, [
      { label: 'Accuracy Overall', value: llmSim.accuracy?.overall != null ? Math.round(llmSim.accuracy.overall) : 'N/A', color: C.gold },
      { label: 'Completeness Overall', value: llmSim.completeness?.overall != null ? Math.round(llmSim.completeness.overall) : 'N/A', color: C.blue },
      { label: 'Consistency Score', value: llmSim.consistency?.consistency_score != null ? Math.round(llmSim.consistency.consistency_score) : 'N/A', color: C.emerald },
      { label: 'Claims Extracted', value: llmSim.accuracy?.claims_extracted ?? 'N/A', color: C.zinc300 },
    ]);
    y += 6;

    // Per-model accuracy
    const perModelAcc = llmSim.accuracy?.per_model ?? {};
    const perModelKeys = Object.keys(perModelAcc);
    if (perModelKeys.length > 0) {
      y = sectionLabel(doc, 'PER-MODEL ACCURACY', y);
      y = drawHBarChart(doc, y, perModelKeys.map(m => ({
        label: m.charAt(0).toUpperCase() + m.slice(1),
        value: typeof perModelAcc[m] === 'number' ? Math.round(perModelAcc[m]) : 0,
        max: 100,
        color: C.gold,
      })));
      y += 8;
    }
  }

  // ── Multi-model comparison ────────────────────────────────────────────────
  if (multiModel.model_friendliness?.per_model) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'MULTI-MODEL FRIENDLINESS', y);
    const pm = multiModel.model_friendliness.per_model as Record<string, number>;
    y = drawHBarChart(doc, y, Object.entries(pm).map(([m, v]) => ({
      label: m.charAt(0).toUpperCase() + m.slice(1),
      value: typeof v === 'number' ? Math.round(v) : 0,
      max: 100,
      color: C.blue,
    })));
    y += 8;
  }

  // ── Page Actions ──────────────────────────────────────────────────────────
  if (pageActions.total_actions > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'PAGE ACTIONS', y);
    y = drawKpiRow(doc, y, [
      { label: 'Total Actions', value: pageActions.total_actions ?? 0, color: C.zinc300 },
      { label: 'High Priority', value: pageActions.high_priority ?? 0, color: C.red },
      { label: 'Current LLM Score', value: pageActions.current_llm_friendliness != null ? Math.round(pageActions.current_llm_friendliness) : 'N/A', color: C.gold },
      { label: 'Predicted Score', value: pageActions.predicted_llm_friendliness != null ? Math.round(pageActions.predicted_llm_friendliness) : 'N/A', color: C.emerald },
    ]);
    y += 6;

    const actions: any[] = (pageActions.actions ?? []).slice(0, 12);
    if (actions.length > 0) {
      y = sectionLabel(doc, 'TOP PAGE ACTIONS', y);
      const actRows = actions.map((a: any) => [
        a.action ? a.action.substring(0, 60) : '—',
        (a.priority ?? '—').toUpperCase(),
        a.category ?? '—',
        a.impact_points != null ? `+${a.impact_points}` : '—',
      ]);
      y = drawTable(doc, y, ['Action', 'Priority', 'Category', 'Impact Pts'], actRows, [250, 60, 110, 60], 12);
      y += 8;
    }
  }

  // ── Model breakdown table (from module_e master_analysis) ─────────────────
  if (modelsList.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, 'BRAND PERFORMANCE BY AI MODEL', y);
    y = drawHBarChart(doc, y, modelsList.map((m: any) => ({
      label: typeof m.model === 'string' ? m.model.charAt(0).toUpperCase() + m.model.slice(1) : 'Model',
      value: typeof m.model_wise_performance_score === 'number' ? Math.round(m.model_wise_performance_score) : 0,
      max: 100,
      color: C.gold,
    })));
    y += 6;

    y = sectionLabel(doc, 'DETAILED MODEL METRICS', y);
    const mRows = modelsList.map((m: any) => [
      typeof m.model === 'string' ? m.model.charAt(0).toUpperCase() + m.model.slice(1) : '—',
      typeof m.model_wise_performance_score === 'number' ? String(Math.round(m.model_wise_performance_score)) : '—',
      typeof m.completeness_score === 'number' ? String(Math.round(m.completeness_score)) : '—',
      typeof m.content_consistency?.score === 'number' ? String(Math.round(m.content_consistency.score)) : '—',
      typeof m.entity_coverage?.score === 'number' ? String(Math.round(m.entity_coverage.score)) : '—',
      typeof m.accuracy_of_generated_response === 'number' ? String(Math.round(m.accuracy_of_generated_response)) : '—',
    ]);
    y = drawTable(doc, y, ['Model', 'Perf.', 'Completeness', 'Consistency', 'Entity Cov.', 'Accuracy'], mRows, [110, 50, 80, 80, 75, 75]);
    y += 8;
  }

  // ── Missing info / knowledge gaps ─────────────────────────────────────────
  const missingFacts: string[] = missingInfo.missing_facts ?? [];
  if (missingFacts.length > 0) {
    if (y > PAGE_BREAK_Y - 40) {
      drawFooter(doc, pageNum++);
      doc.addPage({ size: 'A4', margin: 0 });
      drawPageHeader(doc, title, subtitle, domain);
      y = 102;
    }
    y = sectionLabel(doc, `KNOWLEDGE GAPS — MISSING FACTS (${missingFacts.length})`, y);
    missingFacts.slice(0, 10).forEach((fact: string) => {
      if (y > PAGE_BREAK_Y) {
        drawFooter(doc, pageNum++);
        doc.addPage({ size: 'A4', margin: 0 });
        drawPageHeader(doc, title, subtitle, domain);
        y = 102;
      }
      doc.fillColor(C.red).font('Helvetica-Bold').fontSize(7.5).text('✕', ML, y + 1, { width: 14 });
      doc.fillColor(C.zinc300).font('Helvetica').fontSize(7.5).text(fact, ML + 16, y, { width: CONTENT_W - 16 });
      y += doc.heightOfString(fact, { width: CONTENT_W - 16 }) + 5;
    });
  }

  drawFooter(doc, pageNum);
  return pdfToBuffer(doc);
}

// ═══════════════════════════════════════════════════════════════════════════════
// ── Public API ───────────────────────────────────────────────────────────────
// ═══════════════════════════════════════════════════════════════════════════════

export class ExportPdfService {
  async generate(
    type: string,
    jobId: string,
    userId: string,
    domain: string,
    reportData?: any,
  ): Promise<Buffer> {
    switch (type) {
      case 'weekly-summary':
        return buildWeeklySummaryPdf(jobId, domain, reportData);
      case 'audit-report':
        return buildAuditReportPdf(jobId, userId, domain);
      case 'competitor-report':
        return buildCompetitorAiReportPdf(jobId, domain);
      case 'ai-scorecard':
        return buildAiScorecardPdfV2(jobId, domain);
      case 'serp-analysis':
        return buildSerpAnalysisPdf(jobId, domain);
      case 'competitor-ai-report':
        return buildCompetitorAiReportPdf(jobId, domain);
      default:
        throw new Error(`Unknown report type: ${type}`);
    }
  }
}
